### ISSUE TITLE
Adapting scVI parameters

### ISSUE THREAD

**Issue by mumichae** [theislab/scib#114]
scVI seems to perform very poorly on the integration benchmark. This is likely due to sub-optimal parametrization. Currently the parameter choices were taken from the tutorial, but this may not be the best way to use scVI to compare it with other methods. Note we cannot optimize scVI too much as we don't do the same for other methods either. This would bias our results towards scVI.

Things we could change to improve performance:
- [ ] increase number of epochs
    + from 100 to 400, 1000
    + for some representative datasets to get a good estimate
    + check model fit and when it overfits e.g. Elbo plot
- [ ] in-/decrease `n_latent`
- [ ] use batch-specific `dispersion`?

https://github.com/YosefLab/scVI/blob/975d9d86ba2be3341a07af07d879bca02c06a7ac/scvi/models/vae.py

**Comment by LuckyMD** [comment]
turned out this was just a bug, which was fixed now
