### ISSUE TITLE
Difficulty installing the conda environments

### ISSUE THREAD

**Issue by leahrosen** [theislab/scib#122]
Hi,

I'd like to try your snakemake pipeline on some data of my own. However, I'm having some trouble creating the two conda environments that require scanpy. When trying to create "scIB-python.yml", pip fails, because it can't find scanpy==1.4.5.dev114+gd69832a:

```
Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement scanpy==1.4.5.dev114+gd69832a (from versions: 0.2.1, 0.2.3, 0.2.3.4, 0.2.3.5, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.9.1, 0.3, 0.3.1, 0.3.2, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 1.0, 1.0.1, 1.0.1.post1, 1.0.2, 1.0.3, 1.0.3.post1, 1.0.4, 1.1a1, 1.1a2, 1.1, 1.2.0, 1.2.1, 1.2.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.4.post1, 1.4.5, 1.4.5.post1, 1.4.5.post2, 1.4.5.post3, 1.4.5.1, 1.4.6, 1.5.0a1, 1.5.0, 1.5.1)
ERROR: No matching distribution found for scanpy==1.4.5.dev114+gd69832a
CondaEnvException: Pip failed
```

And when I modify the .yml to just require scanpy==1.4.5, I get the following error:

```
Pip subprocess error:
ERROR: scanpy 1.4.5 has requirement h5py!=2.10.0, but you'll have h5py 2.10.0 which is incompatible.
ERROR: scanpy 1.4.5 has requirement scipy>=1.3, but you'll have scipy 1.2.1 which is incompatible.
ERROR: torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 1.2.0 which is incompatible.
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Any help getting this to work would be very much appreciated!

**Comment by LuckyMD** [comment]
Hi @leahrosen,

If you want to install the same version of scanpy we were using, you will have to use the `pip install git+` syntax as explained here (https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip). We do also have a docker container for this, which should help to run the metrics though. 

As for the version clashes... I don’t think we touched h5py 2.10, but we did use scipy 1.3. Often versions are specified although compatibility with newer versions is still given. We may need to specify versions better in the environment.yaml.

@danielStrobl could you share the docker container and confirm the versions we are using? I’m away from my laptop atm.

**Comment by leahrosen** [comment]
Thank you for your fast response! Unfortunately I can't find the gd69832a commit in the scanpy repo (assuming that is the commit name), so I'm unable to get the full hash. And simply running `pip install git+git://github.com/theislab/scanpy.git@gd69832a` fails because it can't find the commit `gd69832a`. Please let me know if there's something I'm doing wrong here, but I suppose the docker container will solve this problem :) Thanks again!

**Comment by danielStrobl** [comment]
Hi,
you can install the exact version we are using like that:
`pip install git+https://github.com/theislab/scanpy@d69832a662bbb1047b06a081b789856b53a3931e`.
The docker container is not public as of right now, but I can look into putting that on docker-hub

**Comment by danielStrobl** [comment]
Hi,
our docker container can be found here: https://hub.docker.com/repository/docker/strobld/scib
We are using scipy 1.2.1, h5py 2.10.0 and torch 1.2.0.
At the moment scIB only has been tested with the specific scanpy version we are using, so I would recommend installing that

**Comment by jamesbaye** [comment]
I encountered similar issues with the conda environments setup. I however managed to get `scIB-python` to install successfully by commenting the following lines in the `scIB-python.yml` file:
```
#    - pyyaml==5.1.2
#    - scanpy==1.4.5.dev114+gd69832a
#    - torchvision==0.5.0
#    - trvae==0.0.1
#    - trvaep==0.1.0
```

And installing the dev scanpy version from within the conda env with `pip install git+https://github.com/theislab/scanpy@d69832a662bbb1047b06a081b789856b53a3931e` as [suggested previously](https://github.com/theislab/scib/issues/122#issuecomment-642779678).

**Comment by leahrosen** [comment]
I also had the same problem, but after installing scanpy I could install everything except pyyaml (due to an existing installation), and I had to install trvae 1.0.1 instead of 0.0.1, as well as installing the developer version of scanpy leading to the uninstalling of h5py-2.10.0 and installing of h5py-2.9.0, as well as the uninstalling of scipy 1.2.1 and installing of scipy-1.4.1. But so far the scripts are working, though I haven't tested all of the pipeline yet!

**Comment by LuckyMD** [comment]
Thanks for the pointers @jamesbaye! Indeed, you will only need scanpy from those packages to run the metrics. We should remove `trvaep` from the list anyway, as we removed that from the list of methods. 

It would probably be better to correct the way scanpy is installed to a `git+` install. 

Glad things are now working for you @leahrosen!

**Comment by leahrosen** [comment]
Also, @jamesbaye make sure you either have the cell cycle genes saved in a `resources` folder, or you add your specific path to the cell cycle genes to the `score_cell_cycle` function in `scIB/preprocessing.py` (and make sure it's in the same format as adata.var, i.e. if you use Ensembl ID, make sure the gene list is also that.
