### ISSUE TITLE
installation instructions unclear

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/scib#123]
Hi!
I'd like to use scIB to test the quality of dataset integration in a dataset of mine. It is a bit unclear to me what/how I should install. There are installation instructions for scib that are not under the header "Installation" but above, and then there are the conda environment instructions. Should I first install scIB and then the environment? Might be good to clarify this a bit in the readme.
Thanks!
Lisa

**Comment by danielStrobl** [comment]
Hey Lisa!
For the quality metrics, the scIB-python conda environment is enough. I would recommend to install this environment and then install scIB in this environment, as we only tested it with the package versions in this environment. We also have a docker container for this: https://hub.docker.com/repository/docker/strobld/scib/general
Thanks for the input!
Daniel

**Comment by LuckyMD** [comment]
@danielStrobl do you think we should maybe put the python installation instructions for `scIB` also under the heading `Installation`?

**Comment by danielStrobl** [comment]
Yes, I'll add that

**Comment by ccruizm** [comment]
Good day!

I am also trying to run the pipeline using some public data I have collected. However, it is not clear to me how to run the method you have developed. I have installed the three different conda envs, including an additional one with snakemake. How can snakemake activate the different conda env? I am using an HPC with SLURM but when submitting the jobs, it can not find read scanpy from the envs. 

Could you explain more in detail how to run the pipeline, please? thanks in advance!

**Comment by LuckyMD** [comment]
Hey! 
Maybe we should move this conversation to another issue if it gets much longer.

Quickly, the environment with `snakemake` is run on your submit node. Here, you can run the snakemake command to start your various slurm jobs. An example of how I do that is via the command:

`nohup nice snakemake --jobs=75 --local-cores=1 --nolock --configfile config.yaml --cluster="sbatch -t 4-00:00:00 -c 24 --mem-per-cpu 16000  --partition=my_partition --qos=my_queue" all -k &> slurm_output.out &`

This will in turn start the jobs you specify in the `Snakefile`. In the `Snakefile` you can see that the individual commands are run within the various conda environments by e.g., `conda run -n {cfg.py_env} python` where `cfg.py_env` is the name of the conda python environment that you state in your `config.yaml` file. I hope this makes more sense.

If you have further questions, let's continue this in a separate issue.

**Comment by mumichae** [comment]
Revisiting this issue after a lot of code refactoring and resorting into new repos.

This Repo now just contains the code of the scib python package, whereas the [scib-pipeline](https://github.com/theislab/scib-pipeline) contains the actual end-to-end pipeline and installation instructions for different environments (including R dependencies).

I will close this issue for now. If things are still unclear, we should open up new issues based on the new code base and documentation.
