### ISSUE TITLE
pip cannot find scanpy version for python conda environment

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/scib#124]
Hi!

Was trying to install the python conda environment (scIB-python.yml) and got this error:

Collecting scanpy==1.4.5.dev114+gd69832a (from -r /mnt/home/icb/lisa.sikkema/software/condaenv.s3o7wb4g.requirements.txt (line 49))

Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement scanpy==1.4.5.dev114+gd69832a (from -r /mnt/home/icb/lisa.sikkema/software/condaenv.s3o7wb4g.requirements.txt (line 49)) (from versions: 0.2.1, 0.2.3, 0.2.3.4, 0.2.3.5, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.9.1, 0.3, 0.3.1, 0.3.2, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 1.0, 1.0.1, 1.0.1.post1, 1.0.2, 1.0.3, 1.0.3.post1, 1.0.4, 1.1a1, 1.1a2, 1.1, 1.2.0, 1.2.1, 1.2.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.4.post1, 1.4.5, 1.4.5.post1, 1.4.5.post2, 1.4.5.post3, 1.4.5.1, 1.4.6, 1.5.0a1, 1.5.0, 1.5.1)
ERROR: No matching distribution found for scanpy==1.4.5.dev114+gd69832a (from -r /mnt/home/icb/lisa.sikkema/software/condaenv.s3o7wb4g.requirements.txt (line 49))

CondaEnvException: Pip failed

Is it possible you need to adjust the scanpy version?

**Comment by danielStrobl** [comment]
Hey!
Could you try with this env file here? The issue is that we need a specific scanpy version and the pip command seems to have been corrupted we I exported the env. I replaced the scanpy line in this file. If this doesn't work, you can install scanpy manually like this: `pip install git+https://github.com/theislab/scanpy@d69832a662bbb1047b06a081b789856b53a3931e`
[scIB-python.yml.txt](https://github.com/theislab/scib/files/4925205/scIB-python.yml.txt)

**Comment by LuckyMD** [comment]
does that file need the `prefix` line at the bottom?

**Comment by LisaSikkema** [comment]
seems like the scanpy thing worked, I now got a trvae related error though, here it is:

Collecting trvae==0.0.1 (from -r /mnt/home/icb/lisa.sikkema/software/condaenv.vre4s0cr.requirements.txt (line 57))

Pip subprocess error:
  Running command git clone -q https://github.com/theislab/scanpy /tmp/pip-req-build-6i5k7nbk
  Running command git checkout -q d69832a662bbb1047b06a081b789856b53a3931e
  ERROR: Could not find a version that satisfies the requirement trvae==0.0.1 (from -r /mnt/home/icb/lisa.sikkema/software/condaenv.vre4s0cr.requirements.txt (line 57)) (from versions: 1.0, 1.0.1)
ERROR: No matching distribution found for trvae==0.0.1 (from -r /mnt/home/icb/lisa.sikkema/software/condaenv.vre4s0cr.requirements.txt (line 57))


CondaEnvException: Pip failed

**Comment by LuckyMD** [comment]
check if changing to upper case `trVAE` works.

**Comment by LisaSikkema** [comment]
nope same error

**Comment by LuckyMD** [comment]
It looks like @M0hammadL updated trVAE and removed old versions from `pypi` somehow? Should trVAE version 0.0.1 not be downloadable anymore, Mo?

**Comment by danielStrobl** [comment]
I think for the metrics the version of trvae is not particularly important, so I think you can just remove the version number of trvae.

**Comment by LisaSikkema** [comment]
okay after removing the version number for trvae, everything ran successfully (I used trvae without uppercase, as you did in your file Daniel). Thank you!
