### ISSUE TITLE
Did not find X_emb error

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/scib#130]
Hi! I'm getting an error when running metrics.py, it looks as follows:

Options
    type:	embed
    batch_key:	dataset
    label_key:	scgen_labels
    assay:	expression
    organism:	human
    n_hvgs:	1969
    out_prefix:	Barbry_Krasnow_Kropski_Lafyatis_Meyer_Misharin_MisharinNew_Nawijn_Teichmann_log1p_SCGEN_2khvgs_output_embed
    optimised clustering results:	/storage/groups/ml01/workspace/lisa.sikkema/scIB_metrics/Barbry_Krasnow_Kropski_Lafyatis_Meyer_Misharin_MisharinNew_Nawijn_Teichmann_log1p_SCGEN_2khvgs_output_embed_int_nmi.txt
reading adata before integration
AnnData object with n_obs × n_vars = 343717 × 22833 
    obs: 'age', 'age_range', 'anatomical_region', 'anatomical_region_detailed', 'batch', 'dataset', 'disease', 'donor', 'ethnicity', 'ethnicity_mixed', 'last_author/PI', 'lung_vs_nasal', 'original_celltype_ann', 'pack_years', 'sample', 'sample_alias', 'sample_type', 'sampling_method', 'sex', 'smoking', 'total_counts', 'log10_total_counts', 'n_genes_detected', 'mito_frac', 'ribo_frac', 'compl', 'ann_level_1', 'ann_level_2', 'ann_level_3', 'ann_level_4', 'ann_level_5', 'ann_highest_res', 'ann_new', 'subject_type', 'n_counts', 'size_factors', 'scgen_labels'
    var: 'n_cells', 'highly_variable_per_sample', 'highly_variable_per_dataset', 'highly_variable'
    uns: 'anatomical_region_colors', 'ann_level_1_colors', 'ann_level_2_colors', 'ann_level_3_colors', 'dataset_colors', 'last_author', 'lung_vs_nasal_colors', 'neighbors', 'pca', 'scgen_labels_colors', 'sex_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
reading adata after integration
AnnData object with n_obs × n_vars = 343717 × 1969 
    obs: 'age', 'age_range', 'anatomical_region', 'anatomical_region_detailed', 'ann_highest_res', 'ann_level_1', 'ann_level_2', 'ann_level_3', 'ann_level_4', 'ann_level_5', 'ann_new', 'batch', 'compl', 'dataset', 'disease', 'donor', 'ethnicity', 'ethnicity_mixed', 'last_author/PI', 'log10_total_counts', 'lung_vs_nasal', 'mito_frac', 'n_counts', 'n_genes_detected', 'original_celltype_ann', 'pack_years', 'ribo_frac', 'sample', 'sample_alias', 'sample_type', 'sampling_method', 'scgen_labels', 'sex', 'size_factors', 'smoking', 'subject_type', 'total_counts', 'concat_batch'
    uns: 'dataset_colors', 'neighbors', 'pca', 'scgen_labels_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
reduce integrated data:
    HVG selection:	None
    compute neighbourhood graph:	True on X_emb
    precompute PCA:	True
PCA
Nearest Neigbours
Traceback (most recent call last):
  File "metrics.py", line 159, in <module>
    pca=precompute_pca, umap=False)
  File "/mnt/home/icb/lisa.sikkema/software/scib/scIB/preprocessing.py", line 382, in reduce_data
    sc.pp.neighbors(adata, use_rep=use_rep)
  File "/home/icb/lisa.sikkema/miniconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 94, in neighbors
    random_state=random_state,
  File "/home/icb/lisa.sikkema/miniconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/neighbors/__init__.py", line 620, in compute_neighbors
    X = _choose_representation(self._adata, use_rep=use_rep, n_pcs=n_pcs)
  File "/home/icb/lisa.sikkema/miniconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/tools/_utils.py", line 53, in _choose_representation
    'You need to compute it first.'.format(use_rep))
ValueError: Did not find X_emb in `.obsm.keys()`. You need to compute it first.

I do have X_pca in both my objects, could it be that I have to rename it to X_emb?

**Comment by LisaSikkema** [comment]
Might be related to this piece of code in metrics.py (line 132+):


    # case 2: embedding output
    if (type_ == "embed"):
        n_hvgs = None
        embed = "X_emb"
        # legacy check
        if ('emb' in adata_int.uns) and (adata_int.uns['emb']):
            adata_int.obsm["X_emb"] = adata_int.obsm["X_pca"].copy()

**Comment by LuckyMD** [comment]
Ah, yes. So `metrics.py` is designed to work with our Snakemake pipeline, which calls methods from `scIB.ig.runXXX`. In those functions all low dimensional embeddings that are generated by a method are stored in `adata.obsm['X_emb']`. So if you are running this on an scGen output, you would have to store the low-dimensional embedding that you want to evaluate in `adata.obsm['X_emb']`. If you want to evaluate scGen's corrected expression matrix output, then you would need to set `type` to `full`.

**Comment by LisaSikkema** [comment]
great, thanks! should I do that both for the unintegrated and the integrated object? (And I should use X_pca, right?)

**Comment by LuckyMD** [comment]
The unintegrated object should automatically be processed properly. I'm not sure what output scGen gives you... it should give you both the low-dimensional embedding and the corrected expression matrix. It depends on what you want to use and what you want to evaluate.

**Comment by LisaSikkema** [comment]
okay thanks!
