### ISSUE TITLE
kBET not declared / included in installation instructions

### ISSUE THREAD

**Issue by ilibarra** [theislab/scib#150]
Hello,

I do not see kBET declared in the installation instructions and it is not listed in the envs yml files I have seen. Maybe it is not listed. As a consequence I had to manually install it at some point during the pipeline running.

Could you please comment on that? Solutions would be adding kBET to the envs or mention it in the README instructions.

Thanks,

**Comment by danielStrobl** [comment]
Hey,
unfortunately kBET is not available in bioconda so it needs to be installed manually in R with `devtools::install_github('theislab/kBET`).
I don't know if there is a way to automate that in the env.yml file but I don't think there is

**Comment by ilibarra** [comment]
Good morning,

During the `metrics_all` step I was getting this error
`FileNotFoundError: [Errno 2] No such file or directory: 'miniconda3/envs/scIB-python/lib/python3.7/site-packages/scIB/knn_graph/knn_graph.o`
It turns out that after installing kBET with that command the *.o file indicated there this file is not appearing in that location. I know it is in the directory  `scib/scIB/knn_graph/` in this repository, so I made a symbolic link to it. Not sure if this is an appropriate solution but it seems to be working now.

Thanks,

**Comment by danielStrobl** [comment]
Good morning,

to make sure that the `knn_graph`code is optimised for your system, it should be manually compiled using
```
g++ -std=c++11 -O3 knn_graph.cpp -o knn_graph.o
```
You probably don't need to do that as the version in the github repo is already compiled on the icb servers.
This should probably be added to the readme.

**Comment by mumichae** [comment]
@ilibarra Thanks for pointing out these missing dependencies. As they are not purely python, automatic installation is still WIP. I already added install instructions for kBET elsewhere (which should be merged soon) but still need some time to figure out how to incorporate knn_graph code.
