### ISSUE TITLE
Potential error in selecting clusters in score_ioslated_labels

### ISSUE THREAD

**Issue by Hrovatin** [theislab/scib#153]
I was trying to calculate isolated label F1 scores with scIB, but always got returned 0. This might be due to me using a newer scanpy version where clusters are named with integer strings instead of integers. Namely, in the code https://github.com/theislab/scib/blob/4efc3fb4966b2df50e37587c0074e13dac420caa/scIB/metrics.py#L369 where you select the cluster with the most isolated labels cells you extract the index location of the cluster and not the cluster name. This works if clusters are ordered integers, but breaks if they are strings as the target/returned cluster (e.g. index position integer) does not match any of the clusters. 
I corrected this by changing the max_label_per_batch function as follows:
```
def max_label_per_batch(adata, label_key, cluster_key, label, argmax=False):
        sub = adata.obs[adata.obs[label_key] == label].copy()
        label_counts=sub[cluster_key].value_counts()
        if argmax:
            return label_counts.index[label_counts.argmax()]
            # This is the old line
            #return sub[cluster_key].value_counts().argmax()
        return label_counts.max()

**Comment by mumichae** [comment]
Thanks a lot for pointing this out. I had the same issue on my test dataset, but just didn't notice it until now. I included your fix [here](https://github.com/theislab/scib/pull/154)

**Comment by LuckyMD** [comment]
@Hrovatin The score itself should have been correct though, no? As only the index is affected here.

**Comment by Hrovatin** [comment]
> 
> 
> @Hrovatin The score itself should have been correct though, no? As only the index is affected here.

I use a different version of scanpy (I was getting too many errors when I tried to install scIB environments so I gave up). The original code does not retrieve the correct cluster (it retrieves a non existing one as it interprets index as cluster name, which are not the same in my scanpy version) resulting in all scores being 0.

**Comment by LuckyMD** [comment]
@mumichae why did this not happen to us in the metrics run?

**Comment by LuckyMD** [comment]
Also, @ilibarra managed to get the env running with the help @danielStrobl. We haven't updated the instructions yet on github, so it's a bit difficult otherwise. If you want to try again, I hear it's a lot easier now...

**Comment by mumichae** [comment]
@Hrovatin Let me know if this issue is resolved for you. I included your changes here https://github.com/theislab/scib/pull/154
