### ISSUE TITLE
Memory leak in scran normalization

### ISSUE THREAD

**Issue by scottgigante** [theislab/scib#155]
Seems that scran normalization is a) densifying the data and b) not freeing it afterwards.

```
import openproblems
import psutil
import gc
import time
import scIB


def mem_available():
    time.sleep(1)
    gc.collect()
    time.sleep(1)
    return psutil.virtual_memory().available


initial_memory = mem_available()
adata = openproblems.data.zebrafish.load_zebrafish(test=True)
post_load_memory = mem_available()
del adata
post_delete_memory = mem_available()

adata = openproblems.data.zebrafish.load_zebrafish(test=True)
pre_norm_memory = mem_available()
scIB.preprocessing.normalize(adata)
post_norm_memory = mem_available()
del adata
post_norm_delete_memory = mem_available()

import matplotlib.pyplot as plt
import scprep
fig, ax = plt.subplots()
ax.plot(
    range(6), 
    (
        initial_memory,
        post_load_memory,
        post_delete_memory,
        pre_norm_memory,
        post_norm_memory,
        post_norm_delete_memory,
    )
)

scprep.plot.tools.label_axis(
    ax.xaxis, 
    ticks=range(6),
    ticklabels=[
        "initial",
        "load",
        "delete",
        "reload",
        "norm",
        "delete",
    ],
    ticklabel_rotation=45, 
    ticklabel_horizontal_alignment='right'
)

fig.tight_layout()
```

Plot shows available memory at each stage of the process.
![mem_usage](https://user-images.githubusercontent.com/8499679/92754239-a5a5ce80-f358-11ea-9b7e-be45b0347471.png)

Related: https://github.com/singlecellopenproblems/SingleCellOpenProblems/issues/54

**Comment by LuckyMD** [comment]
Hmm, thanks for the bug report. This likely has to do with using an `R` function from python. As `scran` is run in `R`, a copy of the data matrix is made and converted into an `R` matrix object. That object is not deleted at the moment, and therefore the memory is never freed. The `R` kernel is also probably still running the background.

I'm not sure how to close the `R` kernel, but we should be able to delete the `R` object after moving it back at least.

**Comment by scottgigante** [comment]
This seems like a workable solution:

```
def r_garbage_collection():
    rpy2.robjects.r('rm(list=ls())')
    rpy2.robjects.r('gc()')
```

![image](https://user-images.githubusercontent.com/8499679/92775654-96308080-f36c-11ea-97a3-f398a0bab247.png)

**Comment by LuckyMD** [comment]
I just tested more or less this in #156, but it didn't work for me... Maybe there's more than the data object stored in the `R` session though.... 

Ah, you called the python garbage collector afterwards... i thought this would have sufficed in `R`.

**Comment by scottgigante** [comment]
Worth noting too that I actually had to call the python garbage collector multiple times for the freed memory to register in `psutil`, but this shouldn't be necessary for real use. See https://stackoverflow.com/questions/5199334/clearing-memory-used-by-rpy2#comment5873738_5201851

**Comment by LuckyMD** [comment]
Okay, so there could still be a residual issue with the `R` kernel still existing even after the function is closed. Maybe an `ro.r('q()')` works for that as well...

**Comment by scottgigante** [comment]
Just tried -- `ro.r('q()')` closes python too.

**Comment by LuckyMD** [comment]
that's what I feared....

**Comment by LuckyMD** [comment]
I have a worse example with python garbage collection:
![Screenshot 2020-09-11 at 01 49 34](https://user-images.githubusercontent.com/13019956/92826496-0ffa5580-f3d1-11ea-9cb4-209e6ead2650.png)

I'm using `sc.datasets.pbmc3k()` here, as zebrafish loading doesn't work for me cuz of a HTTP error.

**Comment by scottgigante** [comment]
Did you try running `gc.collect()` three times in a row? That made a difference for me.

**Comment by LuckyMD** [comment]
I already am... but I'll try 10 times ;)

**Comment by LuckyMD** [comment]
I've now unloaded modules as well in #156, but haven't yet managed to close the session. Still waiting on an answer in https://github.com/rpy2/rpy2/issues/730. Could you take a look and see if it works any better for you with the solution in the PR?

**Comment by scottgigante** [comment]
Looks good to me. Seems releasing memory back to system is a finicky thing so measuring using psutil is imperfect, but I think this is doing the job. The first time I run this it looks back, second time it looks good.

<details>

```
import psutil
import gc
import time
import scIB
import scanpy as sc
import rpy2.robjects as ro


def mem_available():
    time.sleep(1)
    gc.collect()
    gc.collect()
    gc.collect()
    time.sleep(1)
    return psutil.virtual_memory().available


initial_memory = mem_available()
adata = sc.datasets.pbmc3k()
post_load_memory = mem_available()
del adata
post_delete_memory = mem_available()

adata = sc.datasets.pbmc3k()
pre_norm_memory = mem_available()
scIB.preprocessing.normalize(adata)
post_norm_memory = mem_available()
del adata
post_norm_delete_memory = mem_available()
ro.r("ls()")
ro.r("rm(list=ls())")
ro.r("gc()")
post_gc_memory = mem_available()


import matplotlib.pyplot as plt
import scprep
fig, ax = plt.subplots()
ax.plot(
    range(7), 
    (
        initial_memory,
        post_load_memory,
        post_delete_memory,
        pre_norm_memory,
        post_norm_memory,
        post_norm_delete_memory,
        post_gc_memory
    )
)

scprep.plot.tools.label_axis(
    ax.xaxis, 
    ticks=range(7),
    ticklabels=[
        "initial",
        "load",
        "delete",
        "reload",
        "norm",
        "delete",
        "gc",
    ],
    ticklabel_rotation=45, 
    ticklabel_horizontal_alignment='right'
)
ax.set_ylabel("Memory Available")

fig.tight_layout()
```

</details>

![mem_usage](https://user-images.githubusercontent.com/8499679/92962467-f4c62f00-f43e-11ea-90e1-ea4d40354e59.png)

**Comment by scottgigante** [comment]
Another point: anndata2ri should probably coerce to dgCMatrix. See https://github.com/MarioniLab/scran/issues/70

**Comment by LuckyMD** [comment]
I just saw maybe we can improve further using `rpy2.rinterface.endr()` to end the `R` session in the background. The only problem would be that we can't easily restart that session. I guess this might not be necessary though if we reload `rpy2` every time the function is called.

**Comment by scottgigante** [comment]
Seems like a good idea. The startup cost is low and the chances the user wants to use R again are pretty slim, right?

Also PR https://github.com/theislab/scib/pull/164 addresses my previous comment and should save a lot of time and memory.
