### ISSUE TITLE
Error on R methods if there are all zero genes

### ISSUE THREAD

**Issue by lazappi** [theislab/scib#166]
If a dataset has all zero genes some of the R methods fail. The error comes from when an embedding is stored in a Seurat object, for example from `runHarm()`:

```r
sobj@reductions['X_emb'] <- sobj@reductions$harmony
```

This shouldn't be a problem if people filter their datasets properly but thought I should report it just in case it comes up. Possibly it can be fixed by using `sobj[['X_emb']]` instead but I haven't testing this.

**Comment by danielStrobl** [comment]
Hey Luke,
is it this error?
```
Error: no slot of name "global" for this object of class "DimReduc"
```
We were having issues with the ATAC integration runs for the methods that save an embedding
and haven't fixed that yet, and I think it could be the same issue.

**Comment by lazappi** [comment]
Yep, that's the one! It's weird because if you run it manually in R you get a warning and it still works, but it's enough to kill the pipeline. I can't work out exactly where it is coming from but I suspect it's something in Seurat. 

I am re-running without all zero genes but think I still get the error so maybe that isn't the problem.

**Comment by LuckyMD** [comment]
> Yep, that's the one! It's weird because if you run it manually in R you get a warning and it still works, but it's enough to kill the pipeline.

That's a Snakemake feature. It runs in bash strict mode, which means everything needs to run cleanly without warnings.
