### ISSUE TITLE
benchmarking datasets

### ISSUE THREAD

**Issue by sqjin** [theislab/scib#170]
Hi, thanks for the great benchmarking studies. I am wondering whether the collected real benchmarking datasets are available somewhere. If not, could you please kindly share me the lung dataset ''Lung_atlas_full.h5ad'' so that I can run your preprocessing pipeline [here](https://github.com/theislab/scib/blob/master/notebooks/data_preprocessing/lung/Lung_atlas_preprocessing.ipynb)? Thank you so much!

**Comment by LuckyMD** [comment]
Hi @sqjin,

Thanks for the compliment! The datasets are now available on Figshare (except mouse brain so far, as it takes quite some time to upload). You can find them here: https://figshare.com/articles/dataset/Benchmarking_atlas-level_data_integration_in_single-cell_genomics_-_integration_task_datasets_Immune_and_pancreas_/12420968

This will be in the revised manuscript, and I will tweet about it soon as well.

**Comment by sqjin** [comment]
@LuckyMD Thank you for making it easier to access.

**Comment by AllenWLynch** [comment]
Hi, I was looking to download the Lung dataset as well. On the figshare site, the raw counts are available for the drop-seq cells of the lung dataset, but cells assayed using the 10X protocol do not appear to have raw counts:

```
>>> rna_data = anndata.read_h5ad('data/lung_atlas/data.h5ad')
>>> rna_data = rna_data[rna_data.obs.protocol != 'drop-seq']
>>> rna_data.X.data, rna_data.layers['counts'].data
(array([0.8457227 , 0.8489592 , 0.84656495, ..., 0.8000515 , 1.2165804 ,
        0.7779638 ], dtype=float32),
 array([1.1890177, 1.1957711, 1.190773 , ..., 1.1387753, 2.2072291,
        1.0936011], dtype=float32))
```

I was wondering if the raw counts were available.

Thanks,
AL

**Comment by LuckyMD** [comment]
Hi @AllenWLynch,

For the 10X data of the lung cell atlas we used soupX corrected counts that we got from the data generators directly. This likely represents a better version of the count data (although potentially breaking with NB noise model assumptions). If you're looking for the uncorrected raw counts, it might be good to get in touch with the authors of the Vieira-Braga et al paper directly.
