### ISSUE TITLE
how to use the scib package

### ISSUE THREAD

**Issue by deevdevil88** [theislab/scib#171]
Hi !
I am a bit confused about the best way to use the scib pacakge. I am only interested in running the quality metrics. From the issues page i understood to run the quality metrics i only need the sciB-python conda env . So i have installed this env and also installed the sciB package within this environment.

However now i am not sure how best to run the scib.metrics() function.
I have already run seurat integration on a dataset of interest and have the seurat object stored as an rds file. 

I need some help on how to best use this object and how to now use the scib.metrics function to run the various quality metrics.

Thanks!
Devika

**Comment by danielStrobl** [comment]
Hi Devika,

Our metrics function expects anndata objects as input, so you first need to convert your Seurat object. You can do this with the script `scripts/runPost.py` from the repo.
The simplest way to call the metrics function is to use the metrics script: `scripts/metrics.py`
If you only want to run the metrics, the env you installed is sufficient.

If you plan to evaluate several different methods it might be easier to use the snakemake pipeline.

Best,
Daniel

**Comment by sqjin** [comment]
Hi Daniel @danielStrobl , 

I am also interested in the scIB package and the metrics function. I tried to install the package by `conda env create -f scIB-R-conversion.yml` and `pip install -e .`. It shows that the package is successfully installed `Successfully installed scIB`. 

However,  there is an error when importing the module by ` python -c "import scIB"` in the terminal or `scIB = import("scIB", convert=TRUE)` in R.  Both of them displays "RuntimeError: found a situation in which we try to build a type recursively.  This is known to occur e.g. in ``struct s { void(*callable)(struct s); }''.  Please report if you get this error and really need support for your case.".    

Do you have any idea on this error?   My system is "macOS Mojave" and the python environment is like "/Users/sj/opt/miniconda3/lib/python3.7/ "

Do you @deevdevil88 have such issue when installing the package? 

Thanks,
Suoqin

**Comment by deevdevil88** [comment]
Hi @danielStrobl 
Thank you for getting back to me. For my current project i only want to evaluate the seurat integration method. in the future i would like to use the package to evaluate multiple methods. 
Another question, are there any visualisation plots/notebooks for the various metrics that a user can plot out. What is the output of the the metrics.py script?

@sqjin  i havent yet tested running anything within the scIB-python conda env. But i will let you know if i encounter the same error. I tried creating the conda env with the yml file for my MacOS Catalina, but it wouldnt solve (even without the builds) so i installed it on the linux servers we have at work. 

Thanks,
Devika

**Comment by danielStrobl** [comment]
Hey Suoqin,
You could try to install this environment here: https://github.com/theislab/scib/pull/147, but note that this is still work in progress.
The old enviromnent has some issues and inconsistencies.
We also have a docker container here for much easier setup: https://github.com/danielStrobl/sct-docker

**Comment by danielStrobl** [comment]
Hi @deevdevil88 
The script returns a `.csv` file with all scores, each score has a value between 0 and 1.
For plotting, we have a script in `R/vizualisation` that was used to generate the overview figures  in the manuscript,
but I think it only makes sense to use this script if you have multiple methods to compare the score.

**Comment by deevdevil88** [comment]
hi @danielStrobl 
I see, in that case we can just put it as a supplementary table for the current manuscript. Thanks for your quick response.

For each of the different metrics, having higher values is better or does the trend differ depending on the metric?
Best,
Devika

**Comment by deevdevil88** [comment]
hi @danielStrobl 
I had a question in regards to the metrics.py script. im confused with the --integrated and --unintegrated options. Do i need two ANNdata objects? one with the integrated slot from seurat and one without?

Also for the runPost.py what should be the extension of the output file?

Devika

**Comment by danielStrobl** [comment]
Hi,
yes you need two objects, one before and one after integration.
The extension for the output file should be `.h5ad`.

Daniel

**Comment by deevdevil88** [comment]
Hi @danielStrobl 
thanks!
one more question. Because Seurat as various assays and after integration we have an integration assay
should the after integration object only contain the expression matrices from the integration assay?
and the Pre-integration again contain  all expression matrices from only one of the seurat assays RNA or SCT?
if i only need one expression matrices from the relevant assay , then which one should it be for the quality metrics to work best, counts, log normalised data or scaled.data

Thanks
Devika

**Comment by deevdevil88** [comment]
hi @danielStrobl 
i tried running the runPost.oy script on a seurat object (rds file) containing only an integrated assay and got the following error 
`Traceback` (most recent call last):
  File "./scib/scripts/runPost.py", line 39, in <module>
    runPost(file, out, conos)
  File "./scib/scripts/runPost.py", line 20, in runPost
    adata = scIB.pp.readSeurat(inPath)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/scIB/preprocessing.py", line 470, in readSeurat
    adata = ro.r('as.SingleCellExperiment(sobj)')
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 389, in __call__
    res = self.eval(p)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 192, in __call__
    .__call__(*args, **kwargs))
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 121, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/rpy2/rinterface.py", line 773, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in .validate_names(rownames, ans_rownames, "assay rownames()", "rowData rownames() / rowRanges names()") : 
  assay rownames() must be NULL or identical to rowData rownames() /
  rowRanges names()
`
the command i used after activating the scIB-python conda env was 

python ./scib/scripts/runPost.py -i ./Aldinger_organoid_post_int.rds -o ./Aldinger_organoid_post_int.h5ad

**Comment by LuckyMD** [comment]
> For each of the different metrics, having higher values is better or does the trend differ depending on the metric?

Higher is always better :).

>  if i only need one expression matrices from the relevant assay , then which one should it be for the quality metrics to work best, counts, log normalised data or scaled.data

We have been assuming that scaling the data is part of the integration preprocessing rather than the general data format. So we have used log normalized data as unintegrated. The integrated object should then contain the integrated assay I guess.

Also, the error that you have is an R error that is caused by the call `as.SingleCellExperiment(sobj)` where `sobj` is your Seurat object. This is a Seurat call, so maybe it's better to report the error there. You could see if you have this error also when you just run the command in your normal Seurat environment.

**Comment by deevdevil88** [comment]
Hi!
thank you for getting back to me. I got around the conversion to Anndata by using SeuratDisk to do the conversion before i use the metrics.py script. it seems to have read in my pre.integration and post.integration objects fine but then i got this error with the batch_key column 
Traceback (most recent call last):
  File "./scib/scripts/metrics.py", line 109, in <module>
    if not np.array_equal(adata.obs[batch_key].cat.categories,adata_int.obs[batch_key].cat.categories):
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/pandas/core/generic.py", line 5176, in __getattr__
    return object.__getattribute__(self, name)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/pandas/core/accessor.py", line 175, in __get__
    accessor_obj = self._accessor(obj)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 2593, in __init__
    self._validate(data)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 2603, in _validate
    "Can only use .cat accessor with a " "'category' dtype"
AttributeError: Can only use .cat accessor with a 'category' dtype

now before i do the Seurat to AnnData object conversion, the batch_key column is a factor. Now i am not that familiar with python data types but i assume category dtype are similar to factors in R? would converting the column to a character type in R help? I am not sure what i can do to solve this. On googling this some of the post said its to do with old scanpy code.

thanks
Devika

**Comment by sqjin** [comment]
> Hey Suoqin,
> You could try to install this environment here: #147, but note that this is still work in progress.
> The old enviromnent has some issues and inconsistencies.
> We also have a docker container here for much easier setup: https://github.com/danielStrobl/sct-docker

Thanks Daniel. Looking forward to the official release!  Below is the full error I get and hopefully it will help you address the issues. 
`/Users/sj/opt/miniconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sj/Documents/scib-master/scIB/__init__.py", line 2, in <module>
    from scIB import preprocessing, integration, metrics, clustering 

  File "/Users/sj/Documents/scib-master/scIB/preprocessing.py", line 8, in <module>
    import rpy2.rinterface_lib.callbacks

  File "/Users/sj/opt/miniconda3/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py", line 11, in <module>
    from . import conversion

  File "/Users/sj/opt/miniconda3/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 7, in <module>
    from . import openrlib

  File "/Users/sj/opt/miniconda3/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py", line 43, in <module>
    _get_dataptr_fallback)

  File "/Users/sj/opt/miniconda3/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py", line 28, in _get_symbol_or_fallback
    res = getattr(rlib, symbol)

RuntimeError: found a situation in which we try to build a type recursively.  This is known to occur e.g. in ``struct s { void(*callable)(struct s); }''.  Please report if you get this error and really need support for your case.`

**Comment by LuckyMD** [comment]
@sqjin @deevdevil88 Maybe these errors should have their own issue reports, as we are moving from the original post.

@sqjin: For the latter error, it's always helpful to google this. A quick search showed me you may just be missing one package which you can install via `pip install cffi==1.12.3` as suggested here (https://github.com/Teichlab/cellphonedb/issues/126)

**Comment by LuckyMD** [comment]
@deevdevil88 it looks like you just need to do something like `adata.obs[batch_key] = adata.obs[batch_key].astype(category)` as your batch variable has not yet been converted into a categorical. Please do report these issues separately from here on though, so they are easier to find for others who might run into the same thing.
