### ISSUE TITLE
Error while running the isolated labels metric in the metric.py

### ISSUE THREAD

**Issue by deevdevil88** [theislab/scib#173]
Hello,
It seems like i have got the metrics.py script working on my datasets for the seurat method. However it seems to error on the isolated labels method. I cant work out what exactly is the problem . So anyhelp would be great!

command used
`./scib/scripts/metrics.py -u Aldinger_organoid_pre_int.h5ad -i Aldinger_organoid_post_int.h5ad -o Aldinger_organoid_metrics.csv -m seurat -b dataset -l cell_type --organism human --type full --assay expression --hvgs 2999 -v`

Options
    type:	full
    batch_key:	dataset
    label_key:	cell_type
    assay:	expression
    organism:	human
    n_hvgs:	2999
    setup:	seurat_full
    optimised clustering results:	Aldinger_organoid_metrics_nmi.txt
reading adata before integration
AnnData object with n_obs × n_vars = 70827 × 39660 
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'sample_id', 'RNA_snn_res.1', 'seurat_clusters', 'sample_id_aligned', 'percent.mito', 'S.Score', 'G2M.Score', 'Phase', 'CC.Difference', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.1', 'age', 'pANN_0.25_0.18_63', 'DF.classifications_0.25_0.18_63', 'pANN_0.25_0.21_198', 'DF.classifications_0.25_0.21_198', 'pANN_0.25_0.08_273', 'DF.classifications_0.25_0.08_273', 'samples', 'percent.mt', 'SCT_snn_res.1.5', 'pANN_0.25_0.16_3861', 'DF.classifications_0.25_0.16_3861', 'sample_ids', 'integrated_snn_res.1.5', 'integrated_snn_res.0.8', 'integrated_snn_res.2', 'broad_clusters', 'higher_res_clusters', 'figure_clusters', 'flipped_order', 'sample_id_collapsed', 'sex', 'dataset', 'old.ident', 'stim', 'cell_type'
    var: 'features'
reading adata after integration
AnnData object with n_obs × n_vars = 70827 × 3000 
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'sample_id', 'RNA_snn_res.1', 'seurat_clusters', 'sample_id_aligned', 'percent.mito', 'S.Score', 'G2M.Score', 'Phase', 'CC.Difference', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.1', 'age', 'pANN_0.25_0.18_63', 'DF.classifications_0.25_0.18_63', 'pANN_0.25_0.21_198', 'DF.classifications_0.25_0.21_198', 'pANN_0.25_0.08_273', 'DF.classifications_0.25_0.08_273', 'samples', 'percent.mt', 'SCT_snn_res.1.5', 'pANN_0.25_0.16_3861', 'DF.classifications_0.25_0.16_3861', 'sample_ids', 'integrated_snn_res.1.5', 'integrated_snn_res.0.8', 'integrated_snn_res.2', 'broad_clusters', 'higher_res_clusters', 'figure_clusters', 'flipped_order', 'sample_id_collapsed', 'sex', 'dataset', 'old.ident', 'stim', 'cell_type'
    var: 'features'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
reduce integrated data:
    HVG selection:	None
    compute neighbourhood graph:	True on X_pca
    precompute PCA:	True
PCA
Nearest Neigbours
computing metrics
type:	full
    ASW:	True
    NMI:	True
    ARI:	True
    PCR:	True
    cell cycle:	True
    iso lab F1:	True
    iso lab ASW:	True
    HVGs:	True
    kBET:	True
    LISI:	True
    Trajectory:	False
clustering...
optimised clustering against cell_type
optimal cluster resolution: 2.0
optimal score: 0
saved clustering NMI values to Aldinger_organoid_metrics_nmi.txt
NMI...
ARI...
silhouette score...
PC regression...
covariate: dataset
compute PCA n_comps: 50
covariate: dataset
compute PCA n_comps: 50
cell cycle effect...
Trying to set attribute `.obs` of view, copying.
Trying to set attribute `.obs` of view, copying.
isolated labels...
Traceback (most recent call last):
  File "./scib/scripts/metrics.py", line 249, in <module>
    trajectory_=trajectory_
  File "/ifs/research-groups/cncb/proj028/analyses/scib/scIB/metrics.py", line 1857, in metrics
    cluster=True, n=n_isolated, verbose=False)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/scIB/metrics.py", line 336, in isolated_labels
    label, cluster=cluster, verbose=verbose)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/scIB/metrics.py", line 389, in score_isolated_label
    cluster_key, label, argmax=True)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/scIB/metrics.py", line 380, in max_label_per_batch
    return label_counts.index[label_counts.argmax()]
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4273, in __getitem__
    return getitem(key)
  File "/ifs/research-groups/cncb/proj028/analyses/scib/envs/scib_conda/envs/scIB-python/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 2149, in __getitem__
    values=self._codes[key], dtype=self.dtype, fastpath=True
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Thanks,
Devika

**Comment by LuckyMD** [comment]
This looks similar to previous issue: #153. Have you updated to the latest scIB from github? There was a fix about 2 weeks ago? Could you otherwise take a look @mumichae?

**Comment by deevdevil88** [comment]
hi @LuckyMD 
i only cloned the scIB package two days ago and the scanpy version in my scIB-python one is this pip install git+https://github.com/theislab/scanpy@d69832a662bbb1047b06a081b789856b53a3931e . 

Best,
Devika

**Comment by LuckyMD** [comment]
Okay... this just looks like an `.argmax` vs `.idxmax` issue.

**Comment by deevdevil88** [comment]
can you explain please?
.is it because have less batches? the error was produced when i ran it on a dataset where they batch included only 2 batches...im currently testing another dataset which has 5 batches.

**Comment by LuckyMD** [comment]
No, it might be an updated version of `pandas`, and sth do to with a subsetted dataset maybe having non-contiguous indices. But that's something we can test as well. Can you recreate this with a minimal example?

**Comment by deevdevil88** [comment]
Hi @LuckyMD 
What would be a good minimal example. I can try running the metrics using a seurat integrated object  from their dataset examples? See if that still gives me the same error. 
Also you say about pandas version. I installed my conda env using the yaml file.  I'm on holiday today. But will recreate this with a smaller dataset and get back to you.

**Comment by LuckyMD** [comment]
Could you run only the isolated label metric using the metrics.py script on a dataset from scanpy datasets? Maybe `sc.datasets.pbmc3k()` or another?

**Comment by deevdevil88** [comment]
Sure. But are the scanpy datasets integrated with any method.

Devika

**Comment by LuckyMD** [comment]
No, but you are just testing to see if a metric works or not for the moment, right? Then we can see if it's your environment or the metric, or the dataset.

**Comment by deevdevil88** [comment]
Sure. I imagine inputting the same object as uncorrected and integrated
will not cause as issue for the metrics.py script. I asked because of I
thought it mine. Will post an update when I have run that.

Devika

**Comment by LuckyMD** [comment]
The issue here seems to be finding the isolated label that should be scored, rather than any metric evaluation itself. So it could very well be a package version issue.

**Comment by deevdevil88** [comment]
In that case , I'm gonna create a second version of the scib-python conda
env using the yaml file here #147. As my current env is from the yaml file
in the envs folder with the change to trvae and scanpy versions to get it
to work.

Perhaps that is the problem.

Devika

**Comment by LuckyMD** [comment]
let me know if that works! And enjoy your day off ;).

**Comment by mumichae** [comment]
Hi @deevdevil88,

sorry for the late answer. I looked into the code and it seems to be something with the clustering that is part of the method computation. I'm bot quite sure what could cause this issue, but I suggest we should narrow it down by getting more output, for this I have created an `isolated_label_fix` branch. Just `checkout` that branch and run your command again. The interesting part is the output starting from `isolated label...`, which.might give us some more insight to the problem.

Apart from that, you can also try to recreate the isolated label operations in question manually on your dataset.

```
scIB.preprocessing.reduce_data(adata)
scIB.cl.opt_louvain(adata, label_key="cell_type", batch_key="dataset", cluster_key="iso_label")

print(adata["iso_label"].value_counts())
print(adata["iso_label"].value_counts().argmax())
```

Let me know which output you get.

**Comment by deevdevil88** [comment]
Hi @mumichae 
i will try this and the other potential solutions i spoke with @LuckyMD  earlier this week. I havent had a chance to test things out this week as had other things on my plate. But will get back to you very soon.

Devika

**Comment by LuckyMD** [comment]
Hi @deevdevil88,
We've fixed this function on two occasions since this issue was opened. Is it working for you now?

**Comment by mumichae** [comment]
Hi @deevdevil88, are you still facing this issue or can we close this issue?
