### ISSUE TITLE
ERROR: scanpy==1.4.5.dev114+gd69832a while creating env scIB-python.yml

### ISSUE THREAD

**Issue by z5ouyang** [theislab/scib#175]
under tags: 0.2.0-168-g20b18f1
The following command run unsuccessfully with error related to scanpy 
conda env create -f scIB-python.yml

ERROR:
Collecting scanpy==1.4.5.dev114+gd69832a (from -r /storage/share/scIB/scib/envs/condaenv.iououab3.requirements.txt (line 49))

Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement scanpy==1.4.5.dev114+gd69832a (from -r /storage/share/scIB/scib/envs/condaenv.iououab3.requirements.txt (line 49)) (from versions: 0.2.1, 0.2.3, 0.2.3.4, 0.2.3.5, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.9.1, 0.3, 0.3.1, 0.3.2, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 1.0, 1.0.1, 1.0.1.post1, 1.0.2, 1.0.3, 1.0.3.post1, 1.0.4, 1.1a1, 1.1a2, 1.1, 1.2.0, 1.2.1, 1.2.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.4.post1, 1.4.5, 1.4.5.post1, 1.4.5.post2, 1.4.5.post3, 1.4.5.1, 1.4.6, 1.5.0a1, 1.5.0, 1.5.1, 1.6.0)
ERROR: No matching distribution found for scanpy==1.4.5.dev114+gd69832a (from -r /storage/share/scIB/scib/envs/condaenv.iououab3.requirements.txt (line 49))

**Comment by z5ouyang** [comment]
And:
Collecting trvae==0.0.1 (from -r /storage/share/scIB/scib/envs/condaenv.m6li0yoy.requirements.txt (line 59))

Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement trvae==0.0.1 (from -r /storage/share/scIB/scib/envs/condaenv.m6li0yoy.requirements.txt (line 59)) (from versions: 1.0, 1.0.1, 1.1.1, 1.1.2)
ERROR: No matching distribution found for trvae==0.0.1 (from -r /storage/share/scIB/scib/envs/condaenv.m6li0yoy.requirements.txt (line 59))

**Comment by danielStrobl** [comment]
Hey,
we have a new environment here, could you try this?: https://github.com/theislab/scib/pull/147
Unfortunately the old trvae version is not available anymore and we haven't adapted to the new version yet.
If you have docker, you can also use this container here: https://github.com/danielStrobl/sct-docker

**Comment by z5ouyang** [comment]
For checkout: 20b18f1f6627f16a72d25e1f08c092d901af1ccf
To install scIB-python, I changed to 'scanpy==1.4.3', 'trvae==1.0.1', 'torch==1.4.0' for 'scIB-python.yml', as well as removed 'pyyaml==5.1.2' from 'scIB-python.yml';
To install scIB-R-integration, I changed to 'scanpy==1.4.3' from 'scIB-R-integration.yml';

Hope this helps.
