### ISSUE TITLE
Clean up old timing code

### ISSUE THREAD

**Issue by lazappi** [theislab/scib#180]
As mentioned in #179 there is some old timing code in various places that has not been replaced by the Snakemake benchmarking option including:

- The `timing` field in the config file
- The `-t` option to the integration scripts
- References to `-t` in `Snakefile`
- Code in the integration scripts that does profiling
- (there may be others)

It would be nice if this could be cleaned up to make it clearer what is being used.

**Comment by LuckyMD** [comment]
@danielStrobl this shouldn't be too hard, right? Maybe something for after revisions though.

**Comment by mumichae** [comment]
Adressing this issue in scib-pipeline https://github.com/theislab/scib-pipeline/pull/36
