### ISSUE TITLE
Simulation code 

### ISSUE THREAD

**Issue by M0hammadL** [theislab/scib#191]
@lazappi  Could you please direct me toward the script to generated simulated data as we discussed?

10 batches and each of them has 1 unique cell type and say 5 shared cell types.  Can we also increase the complexity of the problem?

thx

**Comment by lazappi** [comment]
The simulation scripts are here https://github.com/theislab/scib/tree/master/notebooks/data_preprocessing/simulations.

Happy to discuss in more detail somewhere else, just don't want to clutter up this repo.
