### ISSUE TITLE
Scanorama overwrites batch information

### ISSUE THREAD

**Issue by lazappi** [theislab/scib#195]
Scanorama sometimes overwrites the batch information if it is already in a column called "batch". This is corrected for in the `metrics.py` script here https://github.com/theislab/scib/blob/master/scripts/metrics.py#L108-L111 but not in other places like the `save_embeddings.py` script. It may be better to handle it somewhere earlier in the pipeline or the scIB package.

**Comment by LuckyMD** [comment]
Options are:
1. change in scIB.ig.runScanorama
2. PR to Scanorama package
3. Fix in embedding script
4. Fix only in final plots (not in package or pipeline)

**Comment by mumichae** [comment]
Didn't @danielStrobl already submit a PR?

**Comment by danielStrobl** [comment]
I did. https://github.com/brianhie/scanorama/pull/71
However, this still needs some work.

**Comment by brianhie** [comment]
I hopefully addressed some of these issues (thanks for the PR @danielStrobl) with the latest Scanorama release (see Scanorama PR https://github.com/brianhie/scanorama/pull/77) -- did some basic unit testing but I think it should now preserve everything in .obs, .obsm, .var, and .uns.

**Comment by LuckyMD** [comment]
This is great @brianhie! That makes our code a lot more future proof :). We'll update our environment to use the latest scanorama once the revisions are submitted. I'm a bit hesitant to change something a week before we plan to submit ;).

**Comment by mumichae** [comment]
We are now specifying `scanorama==1.7.0`, as the metrics seem reproduce the same results as the older version we used. This issue is fixed once we finalise PR #147

**Comment by mumichae** [comment]
This issue should now be resolved with #147
