### ISSUE TITLE
pca variance explained used as stdev explained

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/scib#196]
Hi there, 

in your scib.metrics.py script, line 735 (pc_regression function) you square the variances explained per pc (and the variable for the variances explained is called "pca_sd"). However, these values are already variances and not standard deviations, and should therefore not be squared. Maybe also good to rename the variable.

**Comment by LuckyMD** [comment]
This is the offending line:
https://github.com/theislab/scib/blob/90609d54ad10d14bb6b081665be41925255f5301/scIB/metrics.py#L735

**Comment by LuckyMD** [comment]
Further issue:
https://github.com/theislab/scib/blob/90609d54ad10d14bb6b081665be41925255f5301/scIB/metrics.py#L726

This should be the other way around according to:
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

**Comment by LuckyMD** [comment]
The latter error is also  important here:
https://github.com/theislab/scib/blob/90609d54ad10d14bb6b081665be41925255f5301/scIB/metrics.py#L727

**Comment by LuckyMD** [comment]
This was fixed in #197
