### ISSUE TITLE
asw batch computed correctly?

### ISSUE THREAD

**Issue by adamgayoso** [theislab/scib#198]
In https://github.com/theislab/scib/blob/90609d54ad10d14bb6b081665be41925255f5301/scIB/metrics.py#L55-L92

It appears the absolute value and 1 minus transformation is taken per cell, where in the manuscript, it's stated that these are done on the asw, which would be the outputs of `silhouette_score`. Do I have this right?

**Comment by LuckyMD** [comment]
Hi Adam,

Thanks a lot for pointing this out! It does seem to be unclear in the methods section. We will definitely update that for revisions. This is very helpful!

I think it's correct to scale per cell before taking the mean here as we want to assess batch mixing (0) as compared to not mixing.

**Comment by LuckyMD** [comment]
This has been updated in the text now for revisions.
