### ISSUE TITLE
test run

### ISSUE THREAD

**Issue by z5ouyang** [theislab/scib#200]
Hi scib team,
I think I finally installed/configured the scib. And found there is a tests folder in the root folder. I am wondering, how to run/verify my installation/configuration is correct?

Thanks in advance.

**Comment by LuckyMD** [comment]
Hi @z5ouyang, 

We have been working to include a test suite in the repository, but haven't finished it yet. Most of the tests are working, but some are still work in progress. The tests folder is more for changes that we do to the code, but you could use it for your environment test as well I guess. Maybe @mumichae could mention which tests should run with `pytest`.

**Comment by z5ouyang** [comment]
Thanks for the reply! I followed the instruction from 'data_preprocessing' in notebook folder for pancreas and simulations. As required in 'DATA_SCENARIOS' section in "config.yaml". With three data scenarios in modified config.yaml, the command "snakemake --configfile config.yaml --cores 8" is running until the following error, is there a requirement of the test data? especially the 'obs'?  

ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/runPP.py', '-i', '/share/scIB/Data/simulations/sim2.h5ad', '-o', '/share/scIB/test/simulations_2/prepare/unscaled/full_feature/adata_pre.RDS', '-b', 'SubBatch', '--hvgs', '0', '-r', '-l']' command failed.  (See above for error)
Traceback (most recent call last):
  File "scripts/runPP.py", line 72, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/runPP.py", line 43, in runPP
    scIB.preprocessing.saveSeurat(adata, outPath, batch, hvgs)
  File "/storage/share/scIB/scib/scIB/preprocessing.py", line 486, in saveSeurat
    ro.globalenv['adata'] = adata
...
ValueError: Converting pandas "Category" series to R factor is only possible when categories are strings.

**Comment by z5ouyang** [comment]
And if I only run the pancreas data,
the error is:
Traceback (most recent call last):
  File "scripts/metrics.py", line 248, in <module>
    trajectory_=trajectory_
  File "/storage/share/scIB/scib/scIB/metrics.py", line 1844, in metrics
    agg_func=np.mean, organism=organism)
  File "/storage/share/scIB/scib/scIB/metrics.py", line 573, in cell_cycle
    score_cell_cycle(raw_sub, organism=organism)
  File "/storage/share/scIB/scib/scIB/preprocessing.py", line 466, in score_cell_cycle
    raise ValueError(f"cell cycle genes not in adata\n organism: {organism}\n varnames: {rand_genes}")
ValueError: cell cycle genes not in adata
 organism: human
 varnames: [b'CHTF8', b'SIGLEC5', b'SOWAHA', b'IBTK', b'GMIP', b'NAT6', b'DIRAS3', b'MRPL17', b'SMPD1', b'OXSR1']


And I check those genes are in original input h5ad, as well as generated h5ad in 'full_feature' but not the h5ad in 'hvg' folder.

**Comment by mumichae** [comment]
Hi,

For testing, so far the  api test should run through with pytest. You can find the pytest requirements in `tests/requirements.txt`. Just install them via pip into your `scIB-python` conda environment. Then call the test

```
pytest tests/api
```

**Comment by z5ouyang** [comment]
@mumichae Thank you for the information. I did that, and got "2 passed, 9 error in 38.91 seconds"
And seems like it related to obtain the data from public domain: the output is very long, this is a small part:
Do you have any suggestion? Thank you in advance!


>                         encode_chunked=req.has_header('Transfer-encoding'))

/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:1317: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <http.client.HTTPSConnection object at 0x7fdcf3e2c588>, method = 'GET', url = '/chanzuckerberg/cellxgene/master/example-dataset/pbmc3k.h5ad', body = None, headers = {'Connection': 'close', 'Host': 'raw.githubusercontent.com', 'User-Agent': 'Python-urllib/3.7'}

    def request(self, method, url, body=None, headers={}, *,
                encode_chunked=False):
        """Send a complete request to the server."""
>       self._send_request(method, url, body, headers, encode_chunked)

**Comment by mumichae** [comment]
Could you please check the higher-level functions that cause the error? As in which part of the testing code was the cause?

**Comment by z5ouyang** [comment]
It seems related to failure of downloading the data (failed certificate verify), please check the later (tests/conftest.py:27:)


/anaconda3/envs/scIB-python/lib/python3.7/ssl.py:853: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

/anaconda3/envs/scIB-python/lib/python3.7/ssl.py:1117: SSLCertVerificationError

During handling of the above exception, another exception occurred:

    @pytest.fixture(scope="module")
    def adata_batch():
>       adata_ref = sc.datasets.pbmc3k_processed()

tests/conftest.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/datasets/__init__.py:299: in pbmc3k_processed
    backup_url='https://raw.githubusercontent.com/chanzuckerberg/cellxgene/master/example-dataset/pbmc3k.h5ad',
/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py:114: in read
    **kwargs,
/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py:518: in _read
    backup_url=backup_url,
/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py:769: in _check_datafile_present_and_download
    _download(backup_url, path)
/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py:752: in _download
    urlretrieve(url, str(path), reporthook=update_to)
/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:247: in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:222: in urlopen
    return opener.open(url, data, timeout)
/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:525: in open
    response = self._open(req, data)
/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:543: in _open
    '_open', req)
/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:503: in _call_chain
    result = func(*args)
/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py:1360: in https_open
    context=self._context, check_hostname=self._check_hostname)

**Comment by mumichae** [comment]
Does this command  work for you in a python console?
```
adata_ref = sc.datasets.pbmc3k_processed()
```
If not, then there might be a temporary issue with server.
@danielStrobl any ideas?

**Comment by mumichae** [comment]
Does this command  work for you in a python console?
```
adata_ref = sc.datasets.pbmc3k_processed()
```
If not, then there might be a temporary issue with server.
@danielStrobl any ideas?

**Comment by mumichae** [comment]
Does this command  work for you in a python console?
```
adata_ref = sc.datasets.pbmc3k_processed()
```
If not, then there might be a temporary issue with server.
@danielStrobl any ideas?

**Comment by z5ouyang** [comment]
If sc is from "import scanpy as sc", then it didn't work:

>>> adata_ref = sc.datasets.pbmc3k_processed()
pbmc3k_processed.h5ad: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/anaconda3/envs/scIB-python/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/anaconda3/envs/scIB-python/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/anaconda3/envs/scIB-python/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/anaconda3/envs/scIB-python/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/datasets/__init__.py", line 299, in pbmc3k_processed
    backup_url='https://raw.githubusercontent.com/chanzuckerberg/cellxgene/master/example-dataset/pbmc3k.h5ad',
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 114, in read
    **kwargs,
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 518, in _read
    backup_url=backup_url,
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 769, in _check_datafile_present_and_download
    _download(backup_url, path)
  File "/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scanpy/readwrite.py", line 752, in _download
    urlretrieve(url, str(path), reporthook=update_to)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/anaconda3/envs/scIB-python/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

**Comment by danielStrobl** [comment]
This is a bug in scanpy. See here:
https://github.com/theislab/scanpy/pull/1472
