### ISSUE TITLE
Bump scanpy requirement?

### ISSUE THREAD

**Issue by scottgigante** [theislab/scib#204]
scanpy<1.6.0 is missing quite a few bugfixes, and the latest `pip` dependency resolver won't allow us to install scib and scanpy 1.6 at the same time. How much work would it be to get scib to work with the latest scanpy?

**Comment by LuckyMD** [comment]
Probably not that much... mainly a find & replace of `adata.uns['neighbors']['connectivites']` to `adata.obsp['connectivities']` I would imagine. But we're just refactoring this repo to split it into 3 separate ones where `scib` itself will only be the methods & metrics package without pipeline and notebooks. So would be hesitant to change this right now. How urgent is this? We should be done with the refactor in ~2 weeks.

**Comment by LuckyMD** [comment]
@danielStrobl @mumichae can you guys see any other possible hindrances?

**Comment by scottgigante** [comment]
It can definitely wait that long, for sure.

**Comment by mumichae** [comment]
How would this affect `anndata`? Currently we have it locked at 0.7.1

**Comment by LuckyMD** [comment]
would need to bump that too i think... or we should anyway
