### ISSUE TITLE
Pass embedding to Isolated label silhouette

### ISSUE THREAD

**Issue by alitinet** [theislab/scib#211]
As far as I got, now it's not possible to pass embeddings other than `X_pca` to `isolated_labels` when computing Isolated labels silhouette score? Is there a particular reason for using only PCA?

Thanks.

**Comment by LuckyMD** [comment]
We do compute isolated label scores on `adata.obsm['X_embedding']` as well. Why would you suggest only X_pca is allowed?

**Comment by alitinet** [comment]
It looks like in `metrics` there's no `embed` parameter in the `isolated_labels()` function, so it's not passed to `score_isolated labels()` and to `silhouette()`, so `embed='X_pca'` is then used in the latter by default. Am I missing something?

**Comment by LuckyMD** [comment]
Hmm, I see what you mean. @mumichae could you check this out? You wrote the function I believe.

**Comment by mumichae** [comment]
Hi @alitinet, thanks for pointing that out. Indeed, the option to include was missing. A fix should be merged soon #213

**Comment by mumichae** [comment]
@alitinet The PR is now merged. If it solves your issue, we can close this issue

**Comment by alitinet** [comment]
Hi @mumichae, yes, it does, thanks!
