### ISSUE TITLE
Update scvi to scvi-tools

### ISSUE THREAD

**Issue by adamgayoso** [theislab/scib#216]
Hello,

It would be great to update the scvi method here to scvi-tools. Should I just make a PR? Are there any considerations for this?

**Comment by LuckyMD** [comment]
Hey! You are absolutely right that this should happen. We've been holding off on updating the methods before publication as it would then no longer be exactly what is in the paper. But if you add a PR, I would merge this right after I tag a version 1.0 at publication. Does that sound good to you?

**Comment by adamgayoso** [comment]
This makes sense to me, but I think we rely on a newer `anndata`, so it might also have to wait for #204 as well.

**Comment by LuckyMD** [comment]
That's something we'll be addressing within the next few weeks anyway to work with open problems.
