### ISSUE TITLE
scib doesn't install with python 3.8 anymore

### ISSUE THREAD

**Issue by danielStrobl** [theislab/scib#222]
Due to the github actions PR and the changed dependenices, scIB does not install with Python 3.8 anymore.
scGen requires tensorflow 1.15 which is not available for python 3.8.

Do we need to have the integration tools as required dependencies?
Or would it be possible to have those as optional dependencies?

**Comment by LuckyMD** [comment]
Please move to optional. We should definitely not have these as required. This might entail moving import statements into functions in `integration.py` though.
