### ISSUE TITLE
runBBKNN returns None if n_obs in [1e5, 2.5e5]

### ISSUE THREAD

**Issue by jamesbaye** [theislab/scib#230]
Appears to be a [bug](https://github.com/theislab/scib/blob/7d11d7959baaebc3ad588356407a78ac2c3271f4/scIB/integration.py#L291).

**Comment by LuckyMD** [comment]
Thanks for pointing that out! We didn't have a dataset between these sizes and therefore must have missed this. Indeed it should be 1e5 for both boundaries. Could you fix this @danielStrobl? I think 1e5 is written in the manuscript at least, but should double check there as well.

**Comment by danielStrobl** [comment]
#231

**Comment by LuckyMD** [comment]
Just for a heads up though... if you intend to use bbknn, i would use it from the original package and adapt the parameters to your dataset.

**Comment by jamesbaye** [comment]
Thanks @LuckyMD, I'm running bbknn alongside several other methods to compare with an in-house method we're developing so default parameters accessible with your current API should be enough for my current analysis. Thanks for the resource!

**Comment by LuckyMD** [comment]
Glad it's useful! We're happy for any feedback to make the package easier to use in case you run into more issues! We're in the process of setting up 3 separate packages to make this one pip installable ideally
