### ISSUE TITLE
mapping_mouse_human.txt file

### ISSUE THREAD

**Issue by JBreunig** [theislab/scib#233]
Might the mapping_mouse_human.txt file be available?  I'm not sure if I'm missing it on FigShare or in one of the directories--or perhaps a script generates it?
Thanks in advance and excellent work!

**Comment by LuckyMD** [comment]
Hi @JBreunig,
I guess this is the name of the gene ortholog mapping file? I don't think we uploaded that anywhere. 
@martaint could you make a PR and upload this to `scib-reproducibility` if I haven't overlooked it somewhere?

**Comment by JBreunig** [comment]
Thanks! And , yes, that is the gene ortholog mapping file needed in this notebook: scib/notebooks/data_preprocessing/immune_cells/merging/Merging_all_mouse.ipynb

> In [17]:
> mapMouse_Human_orth = pd.read_csv('../mapping_mouse_human.txt', sep='\t')
> mapMouse_Human_orth.head()

**Comment by LuckyMD** [comment]
The file was added in #234 and is at: `notebooks/data_preprocessing/immune_cells/merging/mapping_mouse_human.txt`
