### ISSUE TITLE
Cannot install scIB in colab

### ISSUE THREAD

**Issue by ChineseBest** [theislab/scib#235]
Could I utilize scIB in colab? However, I think pip install scIB does not work, and I am still confused about installation. Thanks.

**Comment by LuckyMD** [comment]
Hi @ChineseBest,

At the moment you can only install scIB via a git install. So`pip install git+https://github.com/theislab/scib.git` should work.

We have conda `environment.yaml` files to install the full environment if you want to run the whole pipeline. That can be found in the `scib-pipeline` now.

**Comment by LuckyMD** [comment]
Did this work for you?

**Comment by ChineseBest** [comment]
Yes, it works for me. However, it seems that there exists conflict in some packages between colab version and scib version, so some functions may be affected. In total, it is a good solution. Sorry for my late reply.

**Comment by LuckyMD** [comment]
No problem. If you encounter particular issues, let us know. @mumichae is just working on an updated environment to run the pipeline in https://github.com/theislab/scib-pipeline/pull/6. Maybe that can help with any clashes you face.
