### ISSUE TITLE
Enhancment: any thoughts about including RISC/RPCI 

### ISSUE THREAD

**Issue by JBreunig** [theislab/scib#240]
Have there been any thoughts of including this new method:  https://github.com/bioinfoDZ/RISC  https://www.nature.com/articles/s41587-021-00859-x ?

**Comment by LuckyMD** [comment]
Hey! We have the method in our overview as preprint from 2019, but the code was only recently made available, so we weren't able to include it yet. This would be a good method to include in the open problems version of the benchmarking task though, which we are setting up [here](https://github.com/openproblems-bio/openproblems/pull/241). Maybe you could suggest that in that forum?

**Comment by JBreunig** [comment]
Will do..thanks!
