### ISSUE TITLE
Why I cannot find runSeurat here?

### ISSUE THREAD

**Issue by ChineseBest** [theislab/scib#248]
It seems that runSeurat has been moved out from scIB, so I wonder if I still can use it in python or not? Otherwise maybe in highly variance gene selection I can run seurat v3. I am not very sure.

**Comment by LuckyMD** [comment]
Hi @ChineseBest,

We ran Seurat from R, but used HVG selection in python to select a consistent set of genes. The `runSeurat` method is now in `scib-pipeline` [here](https://github.com/theislab/scib-pipeline)
