### ISSUE TITLE
Questions related to scIB metrics

### ISSUE THREAD

**Issue by ChineseBest** [theislab/scib#259]
/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-1fa9180263ff> in <module>()
      2 import loompy
      3 import copy
----> 4 import scIB

1 frames
/usr/local/lib/python3.7/dist-packages/scIB/clustering.py in <module>()
      5 import scanpy as sc
      6 from scIB import utils
----> 7 from scIB import metrics
      8 
      9 

ImportError: cannot import name 'metrics' from 'scIB' (/usr/local/lib/python3.7/dist-packages/scIB/__init__.py)

I meet this error in colab when I intend to use scIB. I use this code to install it:
pip install git+https://github.com/theislab/scib.git

Anything wrong? Thanks.

**Comment by LuckyMD** [comment]
@mumichae just reformated the metrics file today. I guess this was from before that... Does `from scIB import me` work? Otherwise you can just access metrics via `scIB.me` or `scIB.metrics`.

**Comment by mumichae** [comment]
Fixed in #258
