### ISSUE TITLE
Proper kBet test

### ISSUE THREAD

**Issue by mumichae** [theislab/scib#270]
Currently, kBET is only tested for returning NaN as a result of failing to load the package (or other errors).

In order to fix this, we need

- [ ] environment with R and python (e.g. micromamba env from opsca-viash)
- [ ] new workflow in github actions (or udate the old one)
- [ ] update test

**Comment by Doris-Fu** [comment]
Hi, what's the status on fixing this issue? I'm still getting 'nan' everytime I run cbi.metrics.kBET. No error message or anything else even if I set verbose=False. Thanks

**Comment by LuckyMD** [comment]
Hi @Doris-Fu,

This issue isn't for kBet not working, but for adding a better test for kBET. Maybe you can file a separate issue for this and give us some more information? kBET should be working...
