### ISSUE TITLE
Question about graph connectivity

### ISSUE THREAD

**Issue by HelloWorldLTY** [theislab/scib#271]
I run seurat v3 on DC dataset and observe that there are obvious mismatch among the batch specific cells, however, for its graph connectivity rate, it is very high. I think it is unbelievable. 

Are there any solutions? Thanks.

**Comment by LuckyMD** [comment]
Hey! Graph connectivity is a very coarse metric. The metric only requires all batches per a cell type to be connected to receive a high score. This is a low bar for success. If you're looking for a more sensitive metric, I would recommend trying BatchASW. 

On another note, there was a recent bug fix to this metric as well... when did you run the metric?

**Comment by HelloWorldLTY** [comment]
Hi, for me I have test this batchasw. In addition, I just run this method this noon, and I think I got the correct results.
