### ISSUE TITLE
Use of embed in opt_louvain

### ISSUE THREAD

**Issue by alitinet** [theislab/scib#277]
Hi all,

I have a question about how `opt_louvain` is calculated in case `embed` parameter is given. It looks like if the neighbors were not precomputed, then they are calculated on .X (and thus on 'X_pca' of .X), even if embed was specified to be something other than 'X_pca'. But I think in this case also the neighbors should be computed with `use_rep = embed`? Would appreciate a clarification.

**Comment by LuckyMD** [comment]
Hi @alitinet,

I'm pretty sure this was a bug we fixed last year specifically for opt_louvain in the embedding outputs. @mumichae could you comment on this?
