### ISSUE TITLE
Function documentation 

### ISSUE THREAD

**Issue by lazappi** [theislab/scib#278]
It's awesome that the package is now available from PyPI but there's not a lot of documentation on how to use it. One basic thing would be to have full function docstrings with description of arguments. This is missing from a lot of places at the moment and where it does exist it's sometimes out of date, for example:

https://github.com/theislab/scib/blob/985d8155391fdfbddec024de428308b5a57ee280/scib/metrics/lisi.py#L25-L42

**Comment by LuckyMD** [comment]
I think the docstrings are there for all metrics functions that are actually being used. the `lisi` function is legacy code. @mumichae recently did a large overhaul that added a lot of this documentation. Any comment @mumichae ?

**Comment by lazappi** [comment]
I first place I noticed was actually in the functions for running all the metrics. I wasn't sure what all the arguments were and how the AnnData objects should be structured. I think in general there are some assumed places that various information needs to be stored but I couldn't see that documented anywhere.

**Comment by LuckyMD** [comment]
Thanks for bringing that up. We didn't look at the joint metrics functions in as much detail. But yes, that should be added.

**Comment by mumichae** [comment]
I agree, docstrings are far from complete. I included some more comprehensive function documentations #279
