### ISSUE TITLE
package import error in jupyter notebook

### ISSUE THREAD

**Issue by myylee** [theislab/scib#280]
Hi there, 

I followed your instruction for downloading this directory from GitHub and installing scib using "pip install ."

I started a new Conda environment for this installation and it went smoothly. 

However, when I try to import scib in jupyter notebook, it gives me an error: [Errno 2] No such file or directory: 'git': 'git'

Any idea on what is causing this and how could I solve it? Thank you so much in advance! 

More detailed error message:
![image](https://user-images.githubusercontent.com/66084077/145244992-c68bc2cc-bedd-42d4-8115-6b346004f989.png)
![image](https://user-images.githubusercontent.com/66084077/145245009-f4d2918a-062c-475a-a392-dde00c49fe5f.png)

Best regards,
Michelle

**Comment by LuckyMD** [comment]
Hi Michelle,

Could you check if you get the same error from just running

```
import rpy2
```

and then 
```
import anndata2ri
```

It looks like `anndata2ri` is causing this. Could it be that you haven't initialized the `IRkernel` in Jupyter? You can do this as explained here: https://github.com/IRkernel/IRkernel

**Comment by mumichae** [comment]
Hi Michelle, is this still an issue? It seems as though git is not installed on your system, but it is required by `anndata2ri`.

**Comment by myylee** [comment]
Hi Michaela, 

thanks for following up with me. The previous suggestion worked!

Best regards,
Michelle
