### ISSUE TITLE
Loosen/unpin numpy and h5py dependency requirements

### ISSUE THREAD

**Issue by Zethson** [theislab/scib#283]
Currently `numpy==1.18.1` and `h5py<3` which does not play nicely with the massive container that we need for the book @LuckyMD 

```
episcanpy 0.3.2 requires numpy>=1.21.2, but you have numpy 1.18.1 which is incompatible.
cellxgene 1.0.0 requires fsspec<0.8.0,>=0.4.4, but you have fsspec 2021.11.1 which is incompatible.
cellxgene 1.0.0 requires h5py>=3.0.0, but you have h5py 2.10.0 which is incompatible.
```

Would it be possible to loosen these restrictions?

CC @le-ander @lazappi

**Comment by HelloWorldLTY** [comment]
I agree, numpy 1.21.2 now is required because I cannot run the code successfully based on numpy 1.18.1. Here is the error:
![image](https://user-images.githubusercontent.com/92051566/148669174-52dd9531-68bb-408c-b55d-69ea0bc22194.png)
This should be the version problem existing in numpy.

**Comment by LuckyMD** [comment]
We had to pin numpy at the time due to a particular integration method I believe. But I can't tell you which one that was. Maybe @danielStrobl remembers? In the end, there's always the difficulty of integration method dependencies clashing.

@HelloWorldLTY did this error occur in the environment we propose?

**Comment by Zethson** [comment]
> We had to pin numpy at the time due to a particular integration method I believe. But I can't tell you which one that was.

Then it might be a good idea to make this particular method optional and to escalate it with the method developers :)
But waiting for @danielStrobl memory first...

**Comment by LuckyMD** [comment]
Just to put here what we discussed offline as well: all integration methods are optional at the moment. We can test removing this pin with the test pipeline when @mumichae is back in March. By then, maybe a fork with the pin removed is the best way forward.
