### ISSUE TITLE
Question about metrics updates

### ISSUE THREAD

**Issue by Hrovatin** [theislab/scib#284]
I have downloaded scIB in February 2021 and since I made some custom changes that would be probably be hard to merge with the  latest version due to interface changes of scIB I was wondering if anyone knows if only kBET metric computation had changed or also other metrics. If no other metrics were changed I would just manually correct kBET score in my code instead of trying to merge to the latest scIB version.

**Comment by LuckyMD** [comment]
There was also a change in graph_connectivity since then. But I'm not 100% sure that there wasn't anything else. Can you run both with the test pipeline to check if there are differences?

**Comment by Hrovatin** [comment]
In that case I will try to merge the two.
