### ISSUE TITLE
cant find integration methods

### ISSUE THREAD

**Issue by krushnapavan9** [theislab/scib#285]
cant find the integration methods that are built in R. The following are the methods that are built in R/

> 1. conos
> 2. fastmnn
> 3. seurat
> 4. harmony
> 5. liger

The above methods cant be accessed using the template provided in the documentation

> scib.integration.<method>(adata, batch=<batch_key>)

**Comment by krushnapavan9** [comment]
found them in the another repository [scib-pipeline](https://github.com/theislab/scib-pipeline)

**Comment by LuckyMD** [comment]
Sorry for the confusion. Did you find this unclear in the README?
