### ISSUE TITLE
Cannot install scIB - package error

### ISSUE THREAD

**Issue by johnjeang** [theislab/scib#289]
Hello, 

I am trying to install scIB to evaluate some data integration.  However I am unable to install scIB for whatever reason and from the looks of the error message, it appears to be a problem on the package end.

This following is the response I get after running `pip install git+https://github.com/theislab/scib.git` but I also get the same response when doing `!pip install scib` directly in my jupyter notebook

```
 error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      Error: rpy2 in API mode cannot be built without R in the PATH or R_HOME defined. Correct this or force ABI mode-only by defining the environment variable RPY2_CFFI_MODE=ABI
      ['cffi>=1.10.0', 'jinja2', 'pytz', 'tzlocal']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Has anyone else encountered this before, and does anyone have any light to shed on whether this is a problem on my end or on the end of the package?

Thanks

**Comment by LuckyMD** [comment]
Hi @johnjeang,
It looks like it's looking for an R installation in your environment to install `rpy2`. In scIB we are calling a metric (kBET) which is written in `R`, so you need an R installation on your system to use the package. I realize it sounds strange to require another programming language when installing something on pypi. 

We should probably adapt this to make it installable only via python dependencies if you only want to use a subset of the metrics that is not implemented in `R`.

For now, if you install `R` (and IRkernel, if you're using jupyter I guess), this should work.

**Comment by johnjeang** [comment]
Thank you @LuckyMD, 

That was a quick response and a succinct answer.  I managed to get it working and now that I am reading the error message more carefully it seems obvious that this was the solution.  

Thanks for your patience.

**Comment by LuckyMD** [comment]
Glad it's working now!
