### ISSUE TITLE
Evaluating batch removal using scIB

### ISSUE THREAD

**Issue by XuezhenChen** [theislab/scib#290]
Dear authors,

In your publication, the metrics calculated by scIB were used for benchmarking various data integration algorithms. I am wondering how it's used to evaluate the effect of batch removal on certain datasets. Without a threshold, is there a way to determine whether batch removal is accurate and necessary?
I am considering computing metrics that only require `adata_int` as input for "uncorrected" and "integrated" data and compare them. It'll be great if you can provide some suggestions.

In addition, does the `adata` input has to be "uncorrected"? With harmony integration we only saved harmony embedding in the integrated file, so adata.X would be the uncorrected, normalized expression matrix. While setting `--type embed` I guess it's okay to use the same file as `adata` and `adata_int`, is that correct?

Thanks for your time and patience!

**Comment by LuckyMD** [comment]
Hi @XuezhenChen,

The difficulty with using the metrics to assess whether integration is needed is the baseline. I think the baseline might be quite dataset dependent, and it's tough to say what is a too large batch effect and when is it a biological effect. That's why we primarily focused on relative comparisons between methods.

If I were to check whether batch removal was needed, I would probably take a look at the PCR batch method. This approach evaluates the linear variation that can be explained by batch. Again, this does not have to be 0 if batches differ in biological factors as well though (like cell type composition). You could check how this metric performs vs random batch assignments though.

**Comment by XuezhenChen** [comment]
Hi @LuckyMD,

Thank you for your suggestions. We figured selecting a threshold would be quite dataset dependent and experience-based, too. For now we are only computing metrics for a variety of datasets.

As for the PCR method you mentioned, ideally, if batch effect decreases after integration, the variation explained by batch would decrease as much as possible, which leads to a high scaled PCR score. In this case, does a PCR score of 0 necessarily means bad integration? I asked this because other metrics  I got suggest high graph connectivity or ASW, while PCR batch is 0, so I'm wondering if there's a better way to interpret the results.

Thank you!

**Comment by mumichae** [comment]
Hi @XuezhenChen,

PCR compares the variance contribution of the batch effect before and after integration. If the PCR score is 0 or close to zero, this only means that there is little difference of batch effect (wrt to PCR). This doesn't necessarily mean that the integration is bad, especially if the batch effect wasn't that strong in the first place. Also, keep in mind that PCR can only capture linear effects, so it might miss more complicated batch effects.

**Comment by mumichae** [comment]
Regarding the metrics' anndata input: Depending on the output type of the integration method, different preprocessing steps (PCA, kNN graph, clustering) are assumed by the metric. If you have an embedding output, and compare with the full data matrix, some comparative metrics relying on embedding input will use the embedding provided by the method directly and compare against the PCA. So for your example, you can use the same adata, as `adata.obsm["X_emb"]` and `adata.obsm["X_pca"]` will be the part that is used.

I admit, the metrics usage is not documented very well, I'll be updating those soon. In the meantime I would suggest you follow the preprocessing in the [scib-pipeline metrics script](https://github.com/theislab/scib-pipeline/blob/main/scripts/metrics/metrics.py).
