### ISSUE TITLE
Cell_cycle error: svd_solver can not be used with sparse input

### ISSUE THREAD

**Issue by XuezhenChen** [theislab/scib#291]
Dear authors,

I ran into an error when using `metrics.py` from scib pipeline. It seems like scib failed to calculate cell cycle conservation.

Here is the error output:
```
Traceback (most recent call last):
  File "/SGRNJ03/pipline_test/datascience/chenxuezhen/scib-pipeline/scripts/metrics/metrics.py", line 248, in <module>
    trajectory_=trajectory_
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/metrics.py", line 273, in metrics
    organism=organism
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 77, in cell_cycle
    verbose=verbose
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 171, in get_pcr_before_after
    verbose=verbose
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/pcr.py", line 164, in pc_regression
    return_info=True, svd_solver=svd_solver, copy=True)
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scanpy/preprocessing/_pca.py", line 196, in pca
    'svd_solver: {svd_solver} can not be used with sparse input.\n'
ValueError: svd_solver: {svd_solver} can not be used with sparse input.
```
Please correct me if I'm wrong. From my understanding, variance contribution of cell cycle is calculated by PCR, and the calculation is conducted per batch to eliminate batch effect. In PCR, `svd_solver` for `sc.tl.pca()` is determined by the dimension of each batch subset, and changing `svd_solver` from ‘arpack’ to ‘full’ probably causes this error. In addition, I noticed that in scanpy documentation , options for `svd_solver` in `sc.tl.pca()` are 'arpack', 'randomized', 'auto', and 'lobpcg'. 'full' is not provided as an option.

Does it have anything to do with the scanpy version I'm using? I have scanpy 1.8.2.
Thank you!

**Comment by XuezhenChen** [comment]
Hi @LuckyMD 

Thanks for your response. 

Just to double check with you... In the `pcr.py` script, with the default setting `pcr_var = None` and `n_comps = 50`, if `min(matrix.shape) < 50`, the script changes `svd_solver` to `'full'`, which caused the error.
Do you suggest changing `svd_solver` back to `'arpack'` and use `n_comp = min(matrix.shape) - 1`?

```
 # perform PCA if no variance contributions are given
    if pca_var is None:

        if n_comps is None or n_comps > min(matrix.shape):
            n_comps = min(matrix.shape)

        if n_comps == min(matrix.shape):
            svd_solver = 'full'

        if verbose:
            print("compute PCA")
        pca = sc.tl.pca(matrix, n_comps=n_comps, use_highly_variable=False,
                        return_info=True, svd_solver=svd_solver, copy=True)
        X_pca = pca[0].copy()
        pca_var = pca[3].copy()
        del pca
    else:
        X_pca = matrix
        n_comps = matrix.shape[1]
```

**Comment by LuckyMD** [comment]
Ah, I see. We didn't test this for cases where a batch has <50 cells, so we never actually got to that part it seems. We'd have to check why the `svd_solver` is changed here, but I presume that it is to get all dimensions, which is not possible in `arpack` as you suggest. I will re-open this to get back to this later. It might be best to generate a dense matrix for these cases to use `svd_solver = 'full'`.
