### ISSUE TITLE
Scanorama overwrites batch column in adata.obs: mismatches between batch information and cell barcode

### ISSUE THREAD

**Issue by XuezhenChen** [theislab/scib#292]
Dear authors,

The scanorama integration seems to overwrite my batch column (which is "sample" in adata.obs) and causes mismatches between samples and cells. 
I noticed there was another issue mentioning that scanorama overwrites batch information if the column is called "batch". But in my case the input batch argument was different, and I have scanorama 1.7. In my integrated output it seemed that the batch column was reordered (e.g. Patient1, Patient2, Patient3, etc.) which was different from the original (e.g. starts with Patient2 with random ordering).

I can save the original batch-cell information and correct it after integration, but it's good to know whether this is a problem I should pay more attention to.

Here is my script:
```
python runIntegration.py \
        -m scanorama \
        -i c1613_fig_4a_Processed.h5ad \
        -o c1613_scanorama_samp.h5ad \
        -b sample
```
Thank you!

**Comment by LuckyMD** [comment]
Hi @XuezhenChen,

That's a good spot, but Scanorama is actually not overwriting anything here but instead re-ordering as you suggest. In scanorama the data is separated by batch and then merged again, so your cells should just be re-ordered overall. You can check if the cell to batch label ordering is consistent to confirm this.

**Comment by XuezhenChen** [comment]
Hi @LuckyMD ,

Thank you for your response!
The reason I noticed this change in batch order was that an error was raised when I used scIB to calculate the metrics. The error suggested that the number of cells in each batch did not match before and after scanorama integration.

So I check the number of cells in each batch by doing this (each sample was a batch):
![image](https://user-images.githubusercontent.com/68068468/154267521-c3692deb-5bb7-4591-80ec-fa107ebc1569.png)

It appeared that the batch ids were reordered in scanorama integrated data, but the cell numbers were different.

And in `adata.obs` of scanorama integrated output, it appeared that there were mismatches between cell barcodes and sample (which was provided as the batch label). If nothing had changed, the sample column should match the prefix of cell barcodes as well as the group column.

![image](https://user-images.githubusercontent.com/68068468/154268358-5c8c4712-8ec9-43af-bffb-7ce9522f62cb.png)

I can always fix this manually, but I just wanted to double check with you to make sure I did not mistaken anything... Thanks again for you patience!

**Comment by LuckyMD** [comment]
This is very strange. Did you use the `scIB.ig.scanorama()` function to integrate this? We have a line of code in our `metrics.py` script (in the scib-pipeline repo) to correct for scanorama batch overwriting (and testing if there are discrepancies, which is why you got the error), but it hasn't posed a problem so far. In general, this should ofc not happen. 

What is your `config` file for this run?

**Comment by XuezhenChen** [comment]
I used the `runIntegration.py` from the scib-pipeline repository by specifying the parameters as below:

```
python /SGRNJ03/pipline_test/datascience/chenxuezhen/scib-pipeline/scripts/integration/runIntegration.py \
        -m scanorama \
        -i c1613_fig_4a_Processed.h5ad \
        -o c1613_scanorama_samp.h5ad \
        -b sample
```
To calculate the metrics I simply used `metrics.py` from the scib-pipeline repo:

```
python /SGRNJ03/pipline_test/datascience/chenxuezhen/scib-pipeline/scripts/metrics/metrics.py \
        -u c1613_fig_4a_Processed.h5ad \
        -i c1613_scanorama_samp.h5ad \
        -o c1613_scanorama_metrics.csv \
        -m scanorama \
        -b sample \
        -l annot_full \
        --organism human \
        --type embed \
        --verbose
```
Here is the error message:

```
Traceback (most recent call last):
  File "/SGRNJ03/pipline_test/datascience/chenxuezhen/scib-pipeline/scripts/metrics/metrics.py", line 248, in <module>
    trajectory_=trajectory_
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/metrics.py", line 273, in metrics
    organism=organism
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 77, in cell_cycle
    verbose=verbose
  File "/SGRNJ01/Public/Software/conda_env/scib_pip/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 150, in get_pcr_before_after
    f'batch "{batch}" of batch_key "{batch_key}" has unequal number of '
ValueError: batch "Patient2_Normal" of batch_key "sample" has unequal number of entries before and after integration.
before: 2267 after: 5357
```

**Comment by mumichae** [comment]
I  checked the code again and it turned out to be a bug. I'm addressing it in #309
