### ISSUE TITLE
Use pre-commit

### ISSUE THREAD

**Issue by mumichae** [theislab/scib#305]
### Start using pre-commit

- [x] include working pre-commit config file
- [x] update syntax of all python files
- [x] include dependencies to 'dev' section of setup.cfg
- [x] include README section mentioning the installatio of scib with dev dependencies for developers

### Suggestions from @michalk8 :

> - [x] remove 3.7 CI, add 3.9 (unless you need to support it)
> - [x] use pre-commits (add e.g. black) instead of running raw flake8 (this PR was)
> - [x] add tests coverage
> - [x] not sure how much work, but macOS test CI would be nice to have

with emphasis on the first 2 points

### Notes:

+ This PR targets pre-commit integration and syntax updates. Separate points in the list above should be addressed in separate PRs.
+ We still need to support python 3.7, as this is the version used in scib-pipeline (expect users working with it already)

**Comment by michalk8** [comment]
I'd also recommend purging large files (most likely .ipynb) from the git repo history. When I cloned this repo, I downloaded like 300MiB of data, see also https://rtyley.github.io/bfg-repo-cleaner/.

**Comment by LuckyMD** [comment]
Fully agree! .ipynb files should be moved to `scib-reproducibility`... I thought that already happened mostly.

**Comment by lazappi** [comment]
All the files have been moved but they are still in the git history which gets downloaded when the repository is cloned. They would need to be purged from the history as suggested to stop this happening.

**Comment by mumichae** [comment]
Cleaning the blobs will rewrite the git history, which could break current open pull requests. I'd do this once we have merged some of the recent PRs
