### ISSUE TITLE
Bump rpy2 version?

### ISSUE THREAD

**Issue by lazappi** [theislab/scib#322]
Would it be possible/how much work would it be to bump the **rpy2** dependency version?

The reason I ask is that **rpy2** `v3.4.2` is only compatible with R 3.6 which was released in 2019 and is three versions old. This means that any conda environment which includes **scib** is limited to an old version of R and R packages (for Bioconductor at least). It would be great if this restriction was removed so that more recent versions of R could be used with **scib**.

**Comment by Zethson** [comment]
@mumichae we would really appreciate your help here! This is blocking the best-practices 2.0 project.

Thank you!
