### ISSUE TITLE
scib.me.ilisi_graph: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lisi_svo3el2i/graph_lisi_indices_0.txt'

### ISSUE THREAD

**Issue by guott15** [theislab/scib#333]
Hello, 
    I have encountered a problem when I used scib.me.ilisi_graph, which is:  FileNotFoundError, [Errno 2] No such file or directory: '/tmp/lisi_svo3el2i/graph_lisi_indices_0.txt'.

   This seems that this function should firstly generate files graph_lisi_indices_0.txt in the temporary dirs, but it not, how could I fix this error ? I appreciated your questions

**Comment by LuckyMD** [comment]
Hi @guott15,

This looks like an issue in the C++ function knn_graph.o. Could you try to recompile that for your system based on the instructions in the [README](https://github.com/theislab/scib/blob/main/scib/knn_graph/README.md)?

**Comment by guott15** [comment]
Thanks for your reply, I have solved this problem on the instruction.




guott15
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "theislab/scib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [theislab/scib] scib.me.ilisi_graph: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lisi_svo3el2i/graph_lisi_indices_0.txt' (Issue #333)





 
Hi @guott15,
 
This looks like an issue in the C++ function knn_graph.o. Could you try to recompile that for your system based on the instructions in the README?

**Comment by HelloWorldLTY** [comment]
Hi, I also met this problem. So the pipeline is downloading the cpp file and recompiling it? Thanks.

**Comment by mumichae** [comment]
Hi @HelloWorldLTY, which version did you encounter that problem with? And how did you install the package?
