### ISSUE TITLE
Does scgen uses layers.counts or adata.X normalized counts, and where is this indicated?

### ISSUE THREAD

**Issue by ilibarra** [theislab/scib#335]
Hi,

While reading the current scgen running step at `integration.py`, I notice that the `layers.counts` layer might not be used, and if `adata.X` counts are normalized, then those might be used as input.

Is this the expected behavior? In scvi/scanvi, the method `setup_anndata` contains layers='counts', yet in scgen this argument is not indicated.

scvi/scanvi
`SCVI.setup_anndata(net_adata, layer="counts", batch_key=batch)`
https://github.com/theislab/scib/blob/main/scib/integration.py#L233

scgen.
`SCGEN.setup_anndata(net_adata, batch_key=batch, labels_key=cell_type)`
https://github.com/theislab/scib/blob/main/scib/integration.py#L185

Maybe, internally the `layers.counts` variable is verified by scgen, but at the moment I cannot see it.
https://github.com/theislab/scgen/blob/727748980d1019f89a9f92821601a808f6fe1c9b/scgen/_scgen.py#L749

In case raw counts are the correct input for scgen, adding layer='counts' to L185 might assure this is the case.

Thanks for any comment and I hope this info is broadly useful,

**Comment by ilibarra** [comment]
scgen [here](https://github.com/theislab/scgen) is recommended to use normalized counts. "We recommend to use normalized data....". If using adata.X normalized counts and not layers.counts, then the current setup in scib seems to be then ok.

Thanks.

**Comment by LuckyMD** [comment]
Hey!
Yes, scib uses the standard that `adata.X` contains log-normalized data and counts are stored in `adata.layers['counts']`. That's why `layers` is not set in `setup_anndata` for scGen as well. This was done to follow the scgen tutorial you linked to :).
