### ISSUE TITLE
ilisi scores

### ISSUE THREAD

**Issue by aissav** [theislab/scib#337]
Hi there,

We used your LISI evaluation code to evaluate the pancreatic integrated dataset and compare the scores with those obtained from the R [LISI](https://github.com/immunogenomics/LISI) package. We observed that the iLISI and cLISI scores obtained from both methods (R and your implementation) are different **_(note that we used similar parameters for both methods)._**

I know that your implementation was based on the R package. Could you please tell us what could be the issue behind that?

Thank you very much.

**Comment by LuckyMD** [comment]
Hi @aissav,

Did you use the lisi_graph method or something else? lisi_graph is different from iLISI as it uses the knn graph computed for the dataset and doesn't recompute one. It uses graph-based distances to get more nearest neighbors when needed. This is explained in Supplementary Note 2 of the paper [here](https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-021-01336-8/MediaObjects/41592_2021_1336_MOESM1_ESM.pdf). Hope that helps!
