### ISSUE TITLE
Running SCIB

### ISSUE THREAD

**Issue by hezarfenfly** [theislab/scib#341]
Hello,

I have a couple of questions regarding running the SCIB pipeline,
1- i downloaded the pancreas dataset from: https://figshare.com/articles/dataset/Benchmarking_atlas-level_data_integration_in_single-cell_genomics_-_integration_task_datasets_Immune_and_pancreas_/12420968, i believe that the dataset is normalized and we don't need to preprocess it once again? 

I wanted to use this dataset to integrate batch-to-batch, in other words, i wanted to generate pairs from the pancreas dataset (9 batches -> 36 pairs) and run the other methods on those pairs. 

My question is, how did you run the other integration methods, with or without HVG information? I mean do I need to generate HVG and pass them as input to those methods? Or I will pass the whole dataset?
There are two HVG selection methods in your pipeline, which one do you recommend to use?

Thank you very much.

**Comment by LuckyMD** [comment]
Hi @hezarfenfly,

1. Correct, there is log-scran-normalized data in there
2. We did both with and without HVG selection. Check www.github.com/theislab/scib-pipeline for the implementation details in our snakemake pipeline. For most methods we subsetted the data, but for some we just passed HVGs as a list (everything based on seurat objects).

Good luck with your analysis!

**Comment by hezarfenfly** [comment]
Thank you very much for your reply,

Another question, regarding other methods such as scanorama and BBKNN, how did you evaluate them, i could not see much details about this step in your publication and supplementary, 
for example, BBKN outputs the following:
AnnData object with n_obs × n_vars = 3289 × 19093
    obs: 'tech', 'celltype'
    uns: 'neighbors', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

which data from those above do you consider the integrated matrix?

and for scanorama, it outputs the following:
AnnData object with n_obs × n_vars = 3289 × 19093
    obs: 'tech', 'celltype'
    obsm: 'X_emb', 'X_scanorama'

Can you please provide us with more details?
Thank you very much.
