### ISSUE TITLE
Cannot understand the mean of scib.metrics.pcr_comparison parameter 

### ISSUE THREAD

**Issue by houruiyan** [theislab/scib#348]
Hello scib team, 

I am a beginner at single cell. Now I try to use scib to assess SCALEX's performance. But I cannot understand the mean of scib.metrics.pcr_comparison, especiall the covariate – Key for adata.obs column to regress against. 
These are my intergated adata:
![image](https://user-images.githubusercontent.com/56068158/200261675-cf98e426-ddda-41a0-9f17-c824e99980f4.png)

These are my unintergrated adata. 
![image](https://user-images.githubusercontent.com/56068158/200261793-8ce22839-2bb0-4b19-b7f5-117d91f6d8d0.png)

Then which key I should choose as the value of covariate. 

I am also confused about the scib.metrics.nmi(adata_int, group1, group2, method='arithmetic', nmi_dir=None). I do not know the mean of group1 and group2 . 

Hope to get your help. Thank you !

**Comment by mumichae** [comment]
Please check out the updated [documentation](https://scib.readthedocs.io/en/latest/)

For PCA regression we usually use the batch as covariate to measure the variance contribution of the batch. For NMI and ARI we usually compare the given cell labels with the clustering performed on the integrated data
