### ISSUE TITLE
kBET module not found error is supplanted by an np.nan return

### ISSUE THREAD

**Issue by LuckyMD** [theislab/scib#349]
This needs to be adapted to the same code as below @mumichae 

https://github.com/theislab/scib/blob/77ab015254754baa5ca3380bd592bcc9207241de/scib/metrics/kbet.py#L53-L56

**Comment by mumichae** [comment]
Do you mean that the function should throw an error if kBET is not installed instead of returning NaN?

**Comment by LuckyMD** [comment]
yes... it is already like that in the `kBET_single` function... but it never gets there
