### ISSUE TITLE
GPU support for scib metrics?

### ISSUE THREAD

**Issue by AaronNing** [theislab/scib#352]
Hi, I noticed that some functions could are very slow on large datasets (e.g. `sklearn.metrics.silhouette_score` takes hours on million-scale datasets). Any plans on supporting GPU acceleration with e.g. `cuml.metrics.cluster.silhouette_score`? Thanks.

**Comment by adamgayoso** [comment]
We have GPU support for metrics here:

https://scib-metrics.readthedocs.io/

however we restrict to embedding-based inputs in most cases.

**Comment by AaronNing** [comment]
> We have GPU support for metrics here:
> 
> https://scib-metrics.readthedocs.io/
> 
> however we restrict to embedding-based inputs in most cases.

Great, thanks.
