### ISSUE TITLE
ilisi_graph error

### ISSUE THREAD

**Issue by kostaslazaros** [theislab/scib#357]
I'm having an issue with the ilisi_graph function;

I'm working on a miniconda 64 bit environment using a jupyter notebook.

When I try to run ilisi_graph I get the following error;

"[WinError 193] %1 is not a valid Win32 application"

any tips on how to solve this issue?

**Comment by LuckyMD** [comment]
Hi @kostaslazaros,

It looks like you are running scib on Windows in a 32-bit OS. I'm not sure how your 64-bit miniconda application works with the 32-bit OS. ilisi has a C++ bit of code which has to be compiled on your system. I assume it will have been compiled to take 32-bit data using g++ outside of miniconda... but data may then be passed as 64-bit from your miniconda setup. I don't have any expertise with Windows I'm afraid, so I can't really help fix this.

**Comment by kostaslazaros** [comment]
Hello there!! Happy new year first of all!!!
The issue has been resolved; I ran SCIB on linux and everything works perfectly!!!

Thank you for answering and best regards!!

**Comment by LuckyMD** [comment]
Great that it's working!
