### ISSUE TITLE
Add perfect score metric tests for isolated labels

### ISSUE THREAD

**Issue by LuckyMD** [theislab/scib#359]
We are having some issues in open problems with the iso label ASW metric not giving perfect scores when one-hot-encoded cell type labels are used as embedding (with some jitter). We should add perfect score tests for this metric (and maybe more?) in the repo.

See https://github.com/openproblems-bio/openproblems/issues/685

Would you be able to quickly add this @mumichae ?

**Comment by mumichae** [comment]
I added a test with the random embedding from openproblems and get a perfect score. Is that test sufficient or were you thinking of something else?

**Comment by LuckyMD** [comment]
it's not a random embedding, right? It's the one-hot-encoded cell type embedding... so it should be a perfect embedding. This is exactly what I meant though, thanks :).
