### ISSUE TITLE
louvain deprecation

### ISSUE THREAD

**Issue by deniskristak** [theislab/scib#360]
Hi,
I'm trying to install this software as part of the [EasyBuild](https://easybuilders.github.io/)  package manager. For that, I need to install it from source.
However, my issue is that this package https://pypi.org/project/louvain/ is apparently deprecated and has probably been replaced by https://pypi.org/project/leidenalg/ .
I cannot even access documentation of `louvain`...
So my question is - is the `louvain` package still needed and used or can I simply patch the `setup.cfg` file and ignore it?
Thanks!

**Comment by mumichae** [comment]
Hi, for reproducibility purposes we still want to include louvain in the package. The repository seems to be available at https://github.com/vtraag/louvain-igraph. I could make it an optional dependency though.

**Comment by deniskristak** [comment]
Awesome, thanks for the help
