### ISSUE TITLE
isolated label scores do not return expected results

### ISSUE THREAD

**Issue by danielStrobl** [theislab/scib#367]
https://github.com/theislab/scib/blob/82444efd3e4378c487001e701a4a1209ef954aaa/scib/metrics/isolated_labels.py#L229-L230

This function gives the mean over all cells and not only the mean for the cells that are part of the isolated label.
This leads to much lower scores with the baselines as observed here: https://github.com/openproblems-bio/openproblems/issues/685

**Comment by mumichae** [comment]
should be solved by #370
