### ISSUE TITLE
No such file or directory: '/tmp/lisi_gtjq4lmu/graph_lisi_indices_0.txt'

### ISSUE THREAD

**Issue by BillyChen123** [theislab/scib#386]
When I run this code, I have some trouble.
'''scib.me.clisi_graph(datasets, label_key="batch_2", type_="full")'''

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lisi_gtjq4lmu/graph_lisi_indices_0.txt'

How do I fix it?

**Comment by johnarevalo** [comment]
Try installing from source, as suggested in https://github.com/theislab/scib/issues/308

**Comment by mumichae** [comment]
Closing this for now. Feel free to reopen if this is still an issue
